"use client";

import { useMemo, useState } from "react";
import {
  CalendarRange,
  FileText,
  Film,
  Image as ImageIcon,
  Layers,
  Link2,
  Mic,
  Monitor,
  Paperclip,
  Radio,
  Square,
  Target,
  Upload,
  Wand2,
} from "lucide-react";
import type { AspectRatio, Platform } from "@/types/database";
import { cn } from "@/lib/cn";
import { Button } from "@/components/primitives/Button";
import { Badge } from "@/components/primitives/Badge";
import { Panel } from "@/components/app-ui/Panel";
import { ChoiceChip, LabelledSelect, ToolbarButton } from "@/components/app-ui/Controls";
import { RailList, RailNote, RailPanel, RailRow } from "@/components/app-ui/SummaryRail";
import { ErrorState } from "@/components/app-ui/States";
import {
  GENERATION_STAGES,
  DEFAULT_STAGE,
  estimateCost,
  formatCents,
  requiresConfirmation,
  validatePlanRequest,
  type GenerationStageId,
  type PlanRequest,
  type Quality,
} from "@/lib/content/plan";
import {
  DEFAULT_LENGTH_DAYS,
  GOAL_OPTIONS,
  LENGTH_OPTIONS,
  PLATFORM_OPTIONS,
  QUALITY_OPTIONS,
  RATIO_OPTIONS,
  TEMPLATES,
  TONE_OPTIONS,
  briefPanelCopy,
  costCopy,
  createCopy,
  planSummaryCopy,
} from "@/content/create";

/**
 * The campaign composer.
 *
 * Counts and cost are computed on every change from the same pure module the server
 * uses (`lib/content/plan`), so the number in the summary rail is the number the
 * server will act on. Two implementations of that arithmetic would eventually disagree,
 * and the disagreement would be a bill the user did not agree to.
 *
 * Nothing is generated by this component. It builds a request and hands it to a server
 * action; the safe default stage is "plans only".
 *
 * Layout follows the product's brief-then-plan model: the brief and its shape on
 * the left, the consequences on the right, visible at the moment the user
 * changes something rather than after they submit.
 */

/** Format chips, in the reference's order. Ratio ids come from RATIO_OPTIONS. */
const FORMAT_ICONS: Readonly<Record<AspectRatio, typeof Film>> = {
  "9:16": Film,
  "4:5": ImageIcon,
  "1:1": Square,
  "16:9": Monitor,
  "4:3": Monitor,
  "3:2": ImageIcon,
  custom: Layers,
};

export function Composer({
  onSubmit,
  accountCount,
  defaultLanguage,
}: {
  onSubmit: (payload: FormData) => void;
  accountCount: number;
  defaultLanguage: string;
}) {
  const [prompt, setPrompt] = useState("");
  const [platforms, setPlatforms] = useState<Platform[]>(["instagram", "tiktok"]);
  const [ratios, setRatios] = useState<AspectRatio[]>(["9:16"]);
  const [languages, setLanguages] = useState<string[]>([defaultLanguage]);
  const [concepts, setConcepts] = useState(3);
  const [hooksPerConcept, setHooksPerConcept] = useState(2);
  const [durationSeconds, setDurationSeconds] = useState(20);
  const [quality, setQuality] = useState<Quality>("standard");
  const [withVoiceover, setWithVoiceover] = useState(true);
  const [withThumbnail, setWithThumbnail] = useState(false);
  const [stage, setStage] = useState<GenerationStageId>(DEFAULT_STAGE);
  const [confirmed, setConfirmed] = useState(false);

  // The three campaign-shape controls. Each is persisted: length becomes the
  // campaign's date range, tone reaches the language provider, goal becomes the
  // campaign objective. None of them is a decorative field.
  const [lengthDays, setLengthDays] = useState(String(DEFAULT_LENGTH_DAYS));
  const [tone, setTone] = useState(TONE_OPTIONS[0]?.id ?? "confident");
  const [goal, setGoal] = useState(GOAL_OPTIONS[0]?.id ?? "product_awareness");

  /** Which template configured the current shape, for the selected state. */
  const [templateId, setTemplateId] = useState<string | null>(null);

  const request: PlanRequest = useMemo(
    () => ({
      concepts,
      hooksPerConcept,
      platforms,
      ratios,
      languages,
      accountCount,
      withVoiceover,
      withThumbnail,
      durationSeconds,
      quality,
    }),
    [
      concepts,
      hooksPerConcept,
      platforms,
      ratios,
      languages,
      accountCount,
      withVoiceover,
      withThumbnail,
      durationSeconds,
      quality,
    ],
  );

  const errors = useMemo(() => validatePlanRequest(request), [request]);
  const estimate = useMemo(() => estimateCost(request), [request]);
  const needsConfirmation = requiresConfirmation(estimate.counts);

  // Only the render stage actually spends the full estimate, so confirmation is
  // demanded for that combination rather than for any large plan.
  const gateOnConfirmation = needsConfirmation && stage === "render";
  const promptReady = prompt.trim().length >= 10;
  const canSubmit = promptReady && errors.length === 0 && (!gateOnConfirmation || confirmed);

  function toggle<T>(list: T[], value: T, setter: (next: T[]) => void, atLeastOne = true) {
    const has = list.includes(value);
    const next = has ? list.filter((item) => item !== value) : [...list, value];
    // Never allow an empty selection where the plan needs at least one — the user
    // would otherwise have to guess why the estimate disappeared.
    if (atLeastOne && next.length === 0) return;
    setter(next);
  }

  /**
   * Applies a template's structure only.
   *
   * The brief text is untouched by design — see the note on TEMPLATES. Writing
   * prose the user did not choose would anchor their first campaign on our
   * phrasing, so the template sets the shape and the user supplies the words.
   */
  function applyTemplate(id: string) {
    const template = TEMPLATES.find((item) => item.id === id);
    if (!template) return;
    setTemplateId(id);
    setLengthDays(String(template.days));
    setConcepts(template.concepts);
    setGoal(template.goal);
  }

  return (
    <form
      action={onSubmit}
      className="grid items-start gap-[var(--space-6)] xl:grid-cols-[minmax(0,1fr)_var(--app-summary-rail)]"
    >
      {/* Hidden fields carry the resolved request so the server does not re-derive it
          from loose inputs and risk computing something different. */}
      <input type="hidden" name="prompt" value={prompt} />
      <input type="hidden" name="platforms" value={platforms.join(",")} />
      <input type="hidden" name="ratios" value={ratios.join(",")} />
      <input type="hidden" name="languages" value={languages.join(",")} />
      <input type="hidden" name="concepts" value={concepts} />
      <input type="hidden" name="hooksPerConcept" value={hooksPerConcept} />
      <input type="hidden" name="durationSeconds" value={durationSeconds} />
      <input type="hidden" name="quality" value={quality} />
      <input type="hidden" name="withVoiceover" value={String(withVoiceover)} />
      <input type="hidden" name="withThumbnail" value={String(withThumbnail)} />
      <input type="hidden" name="stage" value={stage} />
      <input type="hidden" name="lengthDays" value={lengthDays} />
      <input type="hidden" name="tone" value={tone} />
      <input type="hidden" name="goal" value={goal} />

      <div className="flex min-w-0 flex-col gap-[var(--space-6)]">
        <BriefPanel
          prompt={prompt}
          onPromptChange={setPrompt}
          promptReady={promptReady}
          canSubmit={canSubmit}
        />

        <ShapePanel
          lengthDays={lengthDays}
          onLengthChange={(next) => {
            setLengthDays(next);
            // The shape no longer matches the template that set it.
            setTemplateId(null);
          }}
          tone={tone}
          onToneChange={setTone}
          goal={goal}
          onGoalChange={(next) => {
            setGoal(next);
            setTemplateId(null);
          }}
          platforms={platforms}
          onPlatformToggle={(id) => toggle(platforms, id, setPlatforms)}
          ratios={ratios}
          onRatioToggle={(id) => toggle(ratios, id, setRatios)}
          quality={quality}
          onQualityChange={setQuality}
          concepts={concepts}
          onConceptsChange={(next) => {
            setConcepts(next);
            setTemplateId(null);
          }}
          hooksPerConcept={hooksPerConcept}
          onHooksChange={setHooksPerConcept}
          durationSeconds={durationSeconds}
          onDurationChange={setDurationSeconds}
          withVoiceover={withVoiceover}
          onVoiceoverToggle={() => setWithVoiceover((value) => !value)}
          withThumbnail={withThumbnail}
          onThumbnailToggle={() => setWithThumbnail((value) => !value)}
          languages={languages}
          onLanguagesChange={setLanguages}
        />

        <TemplatePanel activeId={templateId} onApply={applyTemplate} />
      </div>

      <PlanRail
        estimate={estimate}
        errors={errors.map((error) => error.message)}
        stage={stage}
        onStageChange={(next) => {
          setStage(next);
          // Re-arm confirmation when the expensive option is chosen.
          setConfirmed(false);
        }}
        gateOnConfirmation={gateOnConfirmation}
        confirmed={confirmed}
        onConfirmedChange={setConfirmed}
        canSubmit={canSubmit}
        promptReady={promptReady}
      />
    </form>
  );
}

/** The brief input and its source actions. */
function BriefPanel({
  prompt,
  onPromptChange,
  promptReady,
  canSubmit,
}: {
  prompt: string;
  onPromptChange: (next: string) => void;
  promptReady: boolean;
  canSubmit: boolean;
}) {
  const MAX = 4000;

  return (
    <Panel pad="none" className="overflow-hidden">
      <div className="flex items-center justify-between gap-[var(--space-4)] border-b border-[var(--color-border-hairline)] px-[var(--app-panel-pad)] py-[var(--space-4)]">
        <h2 className="flex items-center gap-[var(--space-2)] font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
          <FileText aria-hidden="true" size={14} strokeWidth={1.5} />
          {briefPanelCopy.heading}
        </h2>

        <span
          className={cn(
            "font-utility text-[length:var(--text-utility-xs)] tabular-nums",
            prompt.length > MAX * 0.9
              ? "text-[color:var(--color-warning)]"
              : "text-[color:var(--color-text-muted)]",
          )}
        >
          {prompt.length.toLocaleString("en-US")} / {MAX.toLocaleString("en-US")}
        </span>
      </div>

      <div className="px-[var(--app-panel-pad)] py-[var(--space-4)]">
        {/* A real label, not placeholder-only instruction. Visually hidden
            because the panel heading already names the field on screen, but the
            hint below it is rendered for everyone — essential instructions
            never live only in a placeholder. */}
        <label htmlFor="campaign-brief" className="sr-only">
          {createCopy.promptLabel}
        </label>

        <textarea
          id="campaign-brief"
          name="promptVisible"
          rows={6}
          value={prompt}
          maxLength={MAX}
          onChange={(event) => onPromptChange(event.target.value)}
          aria-describedby="campaign-brief-hint"
          placeholder={createCopy.examples[0]}
          className={cn(
            "w-full resize-y bg-transparent",
            "text-[length:var(--text-body-s)] leading-[var(--leading-snug)] text-[color:var(--color-text-primary)]",
            "placeholder:italic placeholder:text-[color:var(--color-text-muted)]",
            "focus:outline-none",
          )}
        />

        <p
          id="campaign-brief-hint"
          className="mt-[var(--space-3)] text-[length:var(--text-app-meta)] text-[color:var(--color-text-muted)]"
        >
          {createCopy.promptHint}
        </p>
      </div>

      <div className="flex flex-wrap items-center gap-[var(--space-2)] border-t border-[var(--color-border-hairline)] bg-[var(--color-surface-2)] px-[var(--app-panel-pad)] py-[var(--space-3)]">
        {/* Source actions. Disabled and labelled rather than hidden: the product
            will accept these sources, and a disabled control with a reason is
            more honest than a button that silently does nothing. */}
        <ToolbarButton icon={<Paperclip size={14} strokeWidth={1.5} />} disabled>
          {briefPanelCopy.attachLabel}
        </ToolbarButton>
        <ToolbarButton icon={<Link2 size={14} strokeWidth={1.5} />} disabled>
          {briefPanelCopy.urlLabel}
        </ToolbarButton>
        <ToolbarButton icon={<Upload size={14} strokeWidth={1.5} />} disabled>
          {briefPanelCopy.uploadLabel}
        </ToolbarButton>

        <span className="ml-auto flex items-center gap-[var(--space-2)]">
          <ToolbarButton icon={<Wand2 size={14} strokeWidth={1.5} />} emphasis disabled>
            {briefPanelCopy.enhanceLabel}
          </ToolbarButton>

          {/* The real submit. Placed here as well as in the rail because this is
              where the user's hands are after typing the brief. */}
          <Button type="submit" disabled={!canSubmit}>
            {briefPanelCopy.generateLabel}
          </Button>
        </span>
      </div>

      {!promptReady && prompt.length > 0 && (
        <p className="border-t border-[var(--color-border-hairline)] px-[var(--app-panel-pad)] py-[var(--space-3)] text-[length:var(--text-app-meta)] text-[color:var(--color-text-muted)]">
          Write at least ten characters to continue.
        </p>
      )}
    </Panel>
  );
}

/** Campaign shape: length, tone, goal, formats, channels and output options. */
function ShapePanel({
  lengthDays,
  onLengthChange,
  tone,
  onToneChange,
  goal,
  onGoalChange,
  platforms,
  onPlatformToggle,
  ratios,
  onRatioToggle,
  quality,
  onQualityChange,
  concepts,
  onConceptsChange,
  hooksPerConcept,
  onHooksChange,
  durationSeconds,
  onDurationChange,
  withVoiceover,
  onVoiceoverToggle,
  withThumbnail,
  onThumbnailToggle,
  languages,
  onLanguagesChange,
}: {
  lengthDays: string;
  onLengthChange: (next: string) => void;
  tone: string;
  onToneChange: (next: string) => void;
  goal: string;
  onGoalChange: (next: string) => void;
  platforms: readonly Platform[];
  onPlatformToggle: (id: Platform) => void;
  ratios: readonly AspectRatio[];
  onRatioToggle: (id: AspectRatio) => void;
  quality: Quality;
  onQualityChange: (next: Quality) => void;
  concepts: number;
  onConceptsChange: (next: number) => void;
  hooksPerConcept: number;
  onHooksChange: (next: number) => void;
  durationSeconds: number;
  onDurationChange: (next: number) => void;
  withVoiceover: boolean;
  onVoiceoverToggle: () => void;
  withThumbnail: boolean;
  onThumbnailToggle: () => void;
  languages: readonly string[];
  onLanguagesChange: (next: string[]) => void;
}) {
  return (
    <Panel className="flex flex-col gap-[var(--space-6)]">
      <div className="grid gap-[var(--space-3)] sm:grid-cols-3">
        <LabelledSelect
          label="Campaign length"
          value={lengthDays}
          onChange={onLengthChange}
          options={LENGTH_OPTIONS}
          icon={<CalendarRange size={16} strokeWidth={1.5} />}
        />
        <LabelledSelect
          label="Tone of voice"
          value={tone}
          onChange={onToneChange}
          options={TONE_OPTIONS}
          icon={<Radio size={16} strokeWidth={1.5} />}
        />
        <LabelledSelect
          label="Primary goal"
          value={goal}
          onChange={onGoalChange}
          options={GOAL_OPTIONS}
          icon={<Target size={16} strokeWidth={1.5} />}
        />
      </div>

      <fieldset className="min-w-0">
        <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
          {briefPanelCopy.formatsHeading}
        </legend>

        <div className="mt-[var(--space-4)] flex flex-wrap gap-[var(--space-2)]">
          {RATIO_OPTIONS.map((option) => {
            const Icon = FORMAT_ICONS[option.id];
            return (
              <ChoiceChip
                key={option.id}
                label={option.detail}
                detail={option.label}
                icon={<Icon size={16} strokeWidth={1.5} />}
                selected={ratios.includes(option.id)}
                onToggle={() => onRatioToggle(option.id)}
              />
            );
          })}
        </div>

        <div className="mt-[var(--space-4)] flex flex-wrap gap-[var(--space-2)]">
          {PLATFORM_OPTIONS.map((option) => (
            <ChoiceChip
              key={option.id}
              label={option.label}
              selected={platforms.includes(option.id)}
              onToggle={() => onPlatformToggle(option.id)}
            />
          ))}
        </div>
      </fieldset>

      <fieldset className="min-w-0">
        <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
          Output volume
        </legend>

        <div className="mt-[var(--space-4)] grid gap-[var(--space-4)] sm:grid-cols-2 lg:grid-cols-4">
          <NumberField
            label="Concepts"
            hint="Distinct angles on the brief."
            value={concepts}
            min={1}
            max={100}
            onChange={onConceptsChange}
          />
          <NumberField
            label="Hooks each"
            hint="Openings to test against each other."
            value={hooksPerConcept}
            min={1}
            max={10}
            onChange={onHooksChange}
          />
          <NumberField
            label="Duration"
            hint="Target seconds per video."
            value={durationSeconds}
            min={5}
            max={180}
            onChange={onDurationChange}
          />
          <div className="flex flex-col gap-[var(--space-1)]">
            <label
              htmlFor="composer-languages"
              className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-muted)]"
            >
              Languages
            </label>
            <input
              id="composer-languages"
              value={languages.join(", ")}
              aria-describedby="composer-languages-hint"
              onChange={(event) =>
                onLanguagesChange(
                  event.target.value
                    .split(",")
                    .map((value) => value.trim())
                    .filter(Boolean),
                )
              }
              className={cn(
                "min-h-11 w-full rounded-[var(--radius-sm)] border border-[var(--color-border-hairline)]",
                "bg-[var(--color-surface-2)] px-[var(--space-3)]",
                "text-[length:var(--text-app-cell)] text-[color:var(--color-text-primary)]",
                "transition-colors duration-[var(--dur-instant)]",
                "hover:border-[var(--color-border)]",
              )}
            />
            <p
              id="composer-languages-hint"
              className="text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]"
            >
              Comma separated. Each is a separate script.
            </p>
          </div>
        </div>
      </fieldset>

      <div className="flex flex-wrap items-end justify-between gap-[var(--space-6)]">
        <fieldset className="min-w-0">
          <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
            Quality
          </legend>
          <div className="mt-[var(--space-3)] flex flex-wrap gap-[var(--space-2)]">
            {QUALITY_OPTIONS.map((option) => (
              <ChoiceChip
                key={option.id}
                label={option.label}
                selected={quality === option.id}
                onToggle={() => onQualityChange(option.id)}
              />
            ))}
          </div>
        </fieldset>

        <fieldset className="min-w-0">
          <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
            Include
          </legend>
          <div className="mt-[var(--space-3)] flex flex-wrap gap-[var(--space-2)]">
            <ChoiceChip
              label="Voiceover"
              icon={<Mic size={16} strokeWidth={1.5} />}
              selected={withVoiceover}
              onToggle={onVoiceoverToggle}
            />
            <ChoiceChip
              label="Thumbnails"
              icon={<ImageIcon size={16} strokeWidth={1.5} />}
              selected={withThumbnail}
              onToggle={onThumbnailToggle}
            />
          </div>
        </fieldset>
      </div>
    </Panel>
  );
}

/** Quick templates. Configures the campaign's shape; never writes the brief. */
function TemplatePanel({
  activeId,
  onApply,
}: {
  activeId: string | null;
  onApply: (id: string) => void;
}) {
  return (
    <Panel id="templates" className="scroll-mt-[var(--space-24)]">
      <div className="flex flex-wrap items-baseline justify-between gap-[var(--space-4)]">
        <h2 className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
          {briefPanelCopy.templatesHeading}
        </h2>
        <p className="text-[length:var(--text-app-meta)] text-[color:var(--color-text-muted)]">
          {briefPanelCopy.templatesHint}
        </p>
      </div>

      <ul className="mt-[var(--space-4)] grid gap-[var(--space-3)] sm:grid-cols-2 lg:grid-cols-4">
        {TEMPLATES.map((template) => {
          const active = template.id === activeId;
          return (
            <li key={template.id}>
              <button
                type="button"
                onClick={() => onApply(template.id)}
                aria-pressed={active}
                className={cn(
                  "flex h-full w-full flex-col items-start gap-[var(--space-2)] rounded-[var(--radius-sm)] p-[var(--space-4)] text-left",
                  "transition-colors duration-[var(--dur-instant)] ease-[var(--ease-cut)]",
                  "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-focus)]",
                  active
                    ? "border-2 border-[var(--color-action)] bg-[var(--color-action-wash)] p-[calc(var(--space-4)-1px)]"
                    : "border border-[var(--color-border-hairline)] bg-[var(--color-surface-2)] hover:border-[var(--color-border)]",
                )}
              >
                <span className="text-[length:var(--text-app-cell)] text-[color:var(--color-text-primary)]">
                  {template.label}
                </span>

                <span className="font-utility text-[length:var(--text-utility-xs)] tabular-nums text-[color:var(--color-text-muted)]">
                  {template.range} · {template.concepts} concepts
                </span>

                {/* What the brief must cover. This is the template's actual
                    value — it tells the user what to write rather than writing
                    it for them. */}
                <span className="mt-[var(--space-1)] flex flex-col gap-0.5">
                  {template.covers.map((item) => (
                    <span
                      key={item}
                      className="flex gap-[var(--space-2)] text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]"
                    >
                      <span aria-hidden="true">·</span>
                      {item}
                    </span>
                  ))}
                </span>

                {active && (
                  <span className="mt-auto pt-[var(--space-2)] font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-utility)] text-[color:var(--color-action)]">
                    Applied
                  </span>
                )}
              </button>
            </li>
          );
        })}
      </ul>
    </Panel>
  );
}

/**
 * The plan summary rail.
 *
 * Every figure here is computed by `lib/content/plan` from the current form
 * state — the same module the server re-runs on submit. Nothing is illustrative.
 */
function PlanRail({
  estimate,
  errors,
  stage,
  onStageChange,
  gateOnConfirmation,
  confirmed,
  onConfirmedChange,
  canSubmit,
  promptReady,
}: {
  estimate: ReturnType<typeof estimateCost>;
  errors: readonly string[];
  stage: GenerationStageId;
  onStageChange: (next: GenerationStageId) => void;
  gateOnConfirmation: boolean;
  confirmed: boolean;
  onConfirmedChange: (next: boolean) => void;
  canSubmit: boolean;
  promptReady: boolean;
}) {
  const { counts } = estimate;

  return (
    <aside className="flex min-w-0 flex-col gap-[var(--space-4)] xl:sticky xl:top-[var(--space-6)]">
      <RailPanel title={planSummaryCopy.heading} accent id="plan-summary">
        <p className="text-[length:var(--text-app-meta)] leading-[var(--leading-snug)] text-[color:var(--color-text-secondary)]">
          {planSummaryCopy.intro}
        </p>

        {errors.length > 0 && (
          <div className="mt-[var(--space-4)]">
            <ErrorState
              title="PLAN NOT VALID"
              body={errors.join(" ")}
              reassurance="Nothing has been created and no credits have been used."
            />
          </div>
        )}

        <div className="mt-[var(--space-4)]">
          <RailList>
            <RailRow
              label="Content items"
              value={counts.contentItems.toLocaleString("en-US")}
              icon={<FileText size={14} strokeWidth={1.5} />}
            />
            <RailRow
              label="Variants to publish"
              value={counts.variants.toLocaleString("en-US")}
              icon={<Layers size={14} strokeWidth={1.5} />}
            />
            <RailRow
              label="Videos to generate"
              value={counts.videos.toLocaleString("en-US")}
              icon={<Film size={14} strokeWidth={1.5} />}
            />
            <RailRow
              label="Renders"
              value={counts.renders.toLocaleString("en-US")}
              icon={<Monitor size={14} strokeWidth={1.5} />}
            />
            {counts.voiceovers > 0 && (
              <RailRow
                label="Voiceovers"
                value={counts.voiceovers.toLocaleString("en-US")}
                icon={<Mic size={14} strokeWidth={1.5} />}
              />
            )}
            {counts.publishJobs > 0 && (
              <RailRow
                label="Publishing jobs"
                value={counts.publishJobs.toLocaleString("en-US")}
                icon={<Radio size={14} strokeWidth={1.5} />}
              />
            )}

            <RailRow
              label="Total jobs"
              value={counts.totalJobs.toLocaleString("en-US")}
              divided
            />

            {/* Rendered only when provider throughput is actually known. The
                brief permits a time estimate from measured throughput and from
                nothing else, so with no provider configured there is no row
                here rather than an invented range. */}
            {estimate.estimatedMinutes !== null && (
              <RailRow
                label="Estimated time"
                value={`~${estimate.estimatedMinutes.low}–${estimate.estimatedMinutes.high} min`}
              />
            )}

            {/* Credits first, then the cash equivalent. Credits are the unit the
                user's balance is denominated in, so that is the number that
                answers "can I afford this"; the currency figure is the
                explanation of it, not the headline. */}
            <RailRow
              label="Estimated credits"
              value={estimate.credits.toLocaleString("en-US")}
              emphasis
            />
            <RailRow label="Equivalent cost" value={formatCents(estimate.totalCents)} />
          </RailList>
        </div>

        {estimate.estimatedMinutes === null && (
          <p className="mt-[var(--space-3)] text-[length:var(--text-utility-xs)] leading-[var(--leading-snug)] text-[color:var(--color-text-muted)]">
            {costCopy.noTimeEstimate}
          </p>
        )}
      </RailPanel>

      <RailPanel title={planSummaryCopy.statusHeading} id="plan-status">
        <p className="flex items-center gap-[var(--space-2)] text-[length:var(--text-app-cell)] text-[color:var(--color-text-primary)]">
          {/* Not the machine-working teal: nothing is running yet. A neutral
              settled state, with the word carrying the meaning. */}
          <span
            aria-hidden="true"
            className={cn(
              "size-1.5 shrink-0 rounded-full",
              promptReady
                ? "bg-[var(--color-action)]"
                : "bg-[var(--color-text-muted)]",
            )}
          />
          {promptReady ? planSummaryCopy.readyLabel : planSummaryCopy.blockedLabel}
        </p>
        <p className="mt-[var(--space-2)] text-[length:var(--text-app-meta)] text-[color:var(--color-text-muted)]">
          {promptReady
            ? planSummaryCopy.readyDetail
            : "Write a brief of at least ten characters to continue."}
        </p>
      </RailPanel>

      <RailPanel title={costCopy.stageHeading} id="plan-stage">
        <p className="text-[length:var(--text-app-meta)] leading-[var(--leading-snug)] text-[color:var(--color-text-muted)]">
          {costCopy.stageHint}
        </p>

        <div className="mt-[var(--space-4)] flex flex-col gap-[var(--space-2)]">
          {GENERATION_STAGES.map((option) => (
            <label
              key={option.id}
              className={cn(
                "flex min-h-11 cursor-pointer items-start gap-[var(--space-3)] rounded-[var(--radius-sm)] p-[var(--space-3)]",
                "transition-colors duration-[var(--dur-instant)]",
                stage === option.id
                  ? "border-2 border-[var(--color-action)] bg-[var(--color-action-wash)] p-[calc(var(--space-3)-1px)]"
                  : "border border-[var(--color-border-hairline)] hover:border-[var(--color-border)]",
              )}
            >
              <input
                type="radio"
                name="stageChoice"
                value={option.id}
                checked={stage === option.id}
                onChange={() => onStageChange(option.id)}
                className="sr-only"
              />
              <span
                aria-hidden="true"
                className="w-3 shrink-0 font-utility text-[color:var(--color-action)]"
              >
                {stage === option.id ? "✓" : ""}
              </span>
              <span className="flex min-w-0 flex-col">
                <span className="text-[length:var(--text-app-cell)] text-[color:var(--color-text-primary)]">
                  {option.label}
                  {!option.cheap && (
                    <Badge tone="warning" className="ml-[var(--space-2)]">
                      Spends credits
                    </Badge>
                  )}
                </span>
                <span className="text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]">
                  {option.produces}
                </span>
              </span>
            </label>
          ))}
        </div>

        {gateOnConfirmation && (
          <div className="mt-[var(--space-4)] flex flex-col gap-[var(--space-3)] rounded-[var(--radius-sm)] border border-[var(--color-warning)] p-[var(--space-4)]">
            <p className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-utility)] text-[color:var(--color-warning)]">
              {costCopy.confirmHeading}
            </p>
            <p className="text-[length:var(--text-app-meta)] text-[color:var(--color-text-secondary)]">
              This will create {estimate.counts.totalJobs.toLocaleString("en-US")} jobs and may use
              significant generation credits. Jobs run in controlled batches. Reviewing concepts
              first avoids unnecessary cost.
            </p>
            <label className="flex min-h-11 cursor-pointer items-center gap-[var(--space-3)] text-[length:var(--text-app-meta)] text-[color:var(--color-text-primary)]">
              <input
                type="checkbox"
                name="confirmed"
                checked={confirmed}
                onChange={(event) => onConfirmedChange(event.target.checked)}
                className="size-4"
              />
              {costCopy.confirmCheckboxLabel}
            </label>
          </div>
        )}

        <Button type="submit" size="lg" className="mt-[var(--space-4)] w-full" disabled={!canSubmit}>
          {createCopy.submitLabel}
        </Button>
      </RailPanel>

      <RailNote
        title={planSummaryCopy.whyHeading}
        body={planSummaryCopy.whyBody}
        icon={<Target size={14} strokeWidth={1.5} />}
      />
    </aside>
  );
}

function NumberField({
  label,
  value,
  min,
  max,
  hint,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  hint: string;
  onChange: (next: number) => void;
}) {
  const id = `composer-${label.toLowerCase().replace(/\s+/g, "-")}`;

  return (
    <div className="flex flex-col gap-[var(--space-1)]">
      <label
        htmlFor={id}
        className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-muted)]"
      >
        {label}
      </label>
      <input
        id={id}
        type="number"
        inputMode="numeric"
        min={min}
        max={max}
        value={value}
        aria-describedby={`${id}-hint`}
        onChange={(event) => {
          const next = Number(event.target.value);
          // Clamped on input rather than on submit: an out-of-range value would
          // otherwise silently change the estimate the user is reading.
          if (Number.isFinite(next)) onChange(Math.min(max, Math.max(min, Math.trunc(next))));
        }}
        className={cn(
          "min-h-11 w-full rounded-[var(--radius-sm)] border border-[var(--color-border-hairline)]",
          "bg-[var(--color-surface-2)] px-[var(--space-3)]",
          "font-utility text-[length:var(--text-app-cell)] tabular-nums text-[color:var(--color-text-primary)]",
          "transition-colors duration-[var(--dur-instant)]",
          "hover:border-[var(--color-border)]",
        )}
      />
      <p id={`${id}-hint`} className="text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]">
        {hint}
      </p>
    </div>
  );
}
