"use client";

import { useId, useMemo, useState, type ReactNode } from "react";
import {
  Check,
  ChevronDown,
  FileText,
  Film,
  Image as ImageIcon,
  Layers,
  Link2,
  Mic,
  Monitor,
  Music,
  Paperclip,
  Radio,
  Square,
  Upload,
  Wand2,
} from "lucide-react";
import type { AspectRatio, Platform } from "@/types/database";
import { cn } from "@/lib/cn";
import { Button } from "@/components/primitives/Button";
import { Card, CardBody, CardHeader } from "@/components/app-ui/Card";
import { ErrorState } from "@/components/app-ui/States";
import {
  estimateCost,
  requiresConfirmation,
  validatePlanRequest,
  type PlanRequest,
  type Quality,
} from "@/lib/content/plan";
import {
  DEFAULT_LENGTH_DAYS,
  GOAL_OPTIONS,
  LENGTH_OPTIONS,
  PLATFORM_OPTIONS,
  QUALITY_OPTIONS,
  RATIO_OPTIONS,
  TEMPLATES,
  TONE_OPTIONS,
  briefPanelCopy,
  costCopy,
  createCopy,
  planSummaryCopy,
} from "@/content/create";
import { ProductionModePanel } from "./ProductionModePanel";
import { CreditPanel, FigureList, FigureRow, PanelNote } from "./CreditPanel";
import { PRODUCTION_MODE_DEFAULTS, DEFAULT_PRODUCTION_MODE } from "@/lib/creative/modes";
import {
  DEFAULT_GATE,
  GENERATION_GATES,
  compareToBalance,
  creditsForGate,
  estimateBatch,
  type EstimateRequest,
  type GenerationGateId,
} from "@/lib/creative/estimator";
import type { ProductionMode } from "@/lib/creative/types";

/**
 * The campaign composer.
 *
 * Counts and cost are computed on every change from the same pure modules the server
 * uses (`lib/content/plan` for validation, `lib/creative/estimator` for the price), so
 * the numbers in the plan column are the numbers the server will act on. Two
 * implementations of that arithmetic would eventually disagree, and the disagreement
 * would be a bill the user did not agree to.
 *
 * Nothing is generated by this component. It builds a request and hands it to a server
 * action; the safe default stage is "plans only".
 *
 * Layout follows the product's brief-then-plan model: the brief and its shape on the
 * left, the consequences on the right, visible at the moment the user changes something
 * rather than after they submit. The left column is grouped into four titled cards
 * because a single sixteen-field form gives the eye no place to stop, and the fields
 * genuinely fall into four decisions: what it is about, who it is for, what comes out,
 * and how each reel is built.
 */

/** Character ceiling on the brief. Enforced by `maxLength` as well as reported. */
const BRIEF_MAX = 4000;

/** Format chips, in the reference's order. Ratio ids come from RATIO_OPTIONS. */
const FORMAT_ICONS: Readonly<Record<AspectRatio, typeof Film>> = {
  "9:16": Film,
  "4:5": ImageIcon,
  "1:1": Square,
  "16:9": Monitor,
  "4:3": Monitor,
  "3:2": ImageIcon,
  custom: Layers,
};

/* Field furniture. Sentence case at label size — uppercase in this product is
   reserved for table column headers. */
const labelClasses =
  "text-[length:var(--text-app-label)] font-[var(--weight-strong)] text-[color:var(--text-secondary)]";
const hintClasses = "text-[length:var(--text-app-label)] text-[color:var(--text-muted)]";

/**
 * The shared control shell: 36px, one radius, one border, one focus ring.
 *
 * `font-family: inherit` is explicit because form controls do not inherit the
 * page font by default — without it a `<select>` renders in the platform UI font
 * beside inputs that render in Geist.
 */
const controlClasses = cn(
  "h-9 w-full rounded-[var(--radius-control)] border border-[var(--border-default)]",
  "bg-[var(--surface-primary)] px-[var(--space-3)]",
  "[font-family:inherit] text-[length:var(--text-app-cell)] text-[color:var(--text-primary)]",
  "transition-colors duration-[var(--dur-instant)]",
  "hover:border-[var(--border-strong)]",
  // The control border measures 1.35:1, so focus cannot rely on a border change
  // alone. The ring is the state, and it is never removed.
  "focus:border-[var(--brand-primary)] focus:outline-2 focus:outline-offset-1 focus:outline-[var(--focus-ring)]",
);

export function Composer({
  onSubmit,
  accountCount,
  defaultLanguage,
  creditsAvailable,
  creditsReserved,
  unmetered,
}: {
  onSubmit: (payload: FormData) => void;
  accountCount: number;
  defaultLanguage: string;
  /** Spendable Production Credits, read from the ledger on the server. */
  creditsAvailable: number;
  /** Credits held for work already running. Reporting only — already deducted. */
  creditsReserved: number;
  /** True when no generation provider is configured, so nothing will be billed. */
  unmetered: boolean;
}) {
  const [prompt, setPrompt] = useState("");
  const [mode, setMode] = useState<ProductionMode>(DEFAULT_PRODUCTION_MODE);
  const [withMusic, setWithMusic] = useState(true);
  const [platforms, setPlatforms] = useState<Platform[]>(["instagram", "tiktok"]);
  const [ratios, setRatios] = useState<AspectRatio[]>(["9:16"]);
  const [languages, setLanguages] = useState<string[]>([defaultLanguage]);
  const [concepts, setConcepts] = useState(3);
  const [hooksPerConcept, setHooksPerConcept] = useState(2);
  const [durationSeconds, setDurationSeconds] = useState(20);
  const [quality, setQuality] = useState<Quality>("standard");
  const [withVoiceover, setWithVoiceover] = useState(true);
  const [withThumbnail, setWithThumbnail] = useState(false);
  const [stage, setStage] = useState<GenerationGateId>(DEFAULT_GATE);
  const [confirmed, setConfirmed] = useState(false);

  // The three campaign-shape controls. Each is persisted: length becomes the
  // campaign's date range, tone reaches the language provider, goal becomes the
  // campaign objective. None of them is a decorative field.
  const [lengthDays, setLengthDays] = useState(String(DEFAULT_LENGTH_DAYS));
  const [tone, setTone] = useState(TONE_OPTIONS[0]?.id ?? "confident");
  const [goal, setGoal] = useState(GOAL_OPTIONS[0]?.id ?? "product_awareness");

  /** Which template configured the current shape, for the selected state. */
  const [templateId, setTemplateId] = useState<string | null>(null);

  const request: PlanRequest = useMemo(
    () => ({
      concepts,
      hooksPerConcept,
      platforms,
      ratios,
      languages,
      accountCount,
      withVoiceover,
      withThumbnail,
      durationSeconds,
      quality,
    }),
    [
      concepts,
      hooksPerConcept,
      platforms,
      ratios,
      languages,
      accountCount,
      withVoiceover,
      withThumbnail,
      durationSeconds,
      quality,
    ],
  );

  const errors = useMemo(() => validatePlanRequest(request), [request]);
  const estimate = useMemo(() => estimateCost(request), [request]);
  const needsConfirmation = requiresConfirmation(estimate.counts);

  /**
   * The mode-aware estimate, shared by the selector and the credit card.
   *
   * Computed from the same pure module the server reserves against, so the
   * number shown here is the number that will be held. Two implementations of
   * this arithmetic would eventually disagree, and the disagreement would be a
   * reservation the user did not agree to.
   */
  const modeRequest: Omit<EstimateRequest, "mode"> = useMemo(
    () => ({
      concepts,
      hooksPerConcept,
      platforms,
      ratios,
      languages,
      accountCount,
      withVoiceover,
      withThumbnail,
      withMusic,
      durationSeconds,
      quality,
    }),
    [
      concepts,
      hooksPerConcept,
      platforms,
      ratios,
      languages,
      accountCount,
      withVoiceover,
      withThumbnail,
      withMusic,
      durationSeconds,
      quality,
    ],
  );

  // Every mode is priced, not just the selected one — the selector shows what
  // switching would cost, which is the comparison the control exists to support.
  const batchCredits = useMemo(() => {
    const entries = PRODUCTION_MODE_DEFAULTS.map(
      (definition) =>
        [definition.id, estimateBatch({ ...modeRequest, mode: definition.id }).credits] as const,
    );
    return Object.fromEntries(entries) as Record<ProductionMode, number>;
  }, [modeRequest]);

  const modeEstimate = useMemo(
    () => estimateBatch({ ...modeRequest, mode }),
    [modeRequest, mode],
  );

  const comparison = useMemo(
    () => compareToBalance(modeEstimate, creditsAvailable),
    [modeEstimate, creditsAvailable],
  );

  // What each gate would spend under the selected mode, so the stage chooser
  // states a cost rather than a vague "spends credits" warning.
  const gateCredits = useMemo(() => {
    const entries = GENERATION_GATES.map(
      (gate) => [gate.id, creditsForGate(modeEstimate, gate.id)] as const,
    );
    return Object.fromEntries(entries) as Record<GenerationGateId, number>;
  }, [modeEstimate]);

  // Only the render stage actually spends the full estimate, so confirmation is
  // demanded for that combination rather than for any large plan.
  const gateOnConfirmation = needsConfirmation && stage === "render";
  const promptReady = prompt.trim().length >= 10;

  /**
   * An unaffordable batch cannot be submitted.
   *
   * Blocked in the UI as well as on the server: the server reservation is the
   * real guard, but letting the button through would take the user to an error
   * page for something the page already knew.
   *
   * Exempt when unmetered — with no provider configured the batch runs on the
   * mock and reserves nothing, so a zero balance must not block it.
   */
  const affordable = unmetered || comparison.affordable;
  const canSubmit =
    promptReady && errors.length === 0 && affordable && (!gateOnConfirmation || confirmed);

  function toggle<T>(list: T[], value: T, setter: (next: T[]) => void, atLeastOne = true) {
    const has = list.includes(value);
    const next = has ? list.filter((item) => item !== value) : [...list, value];
    // Never allow an empty selection where the plan needs at least one — the user
    // would otherwise have to guess why the estimate disappeared.
    if (atLeastOne && next.length === 0) return;
    setter(next);
  }

  /**
   * Applies a template's structure only.
   *
   * The brief text is untouched by design — see the note on TEMPLATES. Writing
   * prose the user did not choose would anchor their first campaign on our
   * phrasing, so the template sets the shape and the user supplies the words.
   */
  function applyTemplate(id: string) {
    const template = TEMPLATES.find((item) => item.id === id);
    if (!template) return;
    setTemplateId(id);
    setLengthDays(String(template.days));
    setConcepts(template.concepts);
    setGoal(template.goal);
  }

  return (
    <form
      action={onSubmit}
      className="grid grid-cols-1 items-start gap-[var(--app-panel-gap)] xl:grid-cols-12"
    >
      {/* Hidden fields carry the resolved request so the server does not re-derive it
          from loose inputs and risk computing something different. */}
      <input type="hidden" name="prompt" value={prompt} />
      <input type="hidden" name="platforms" value={platforms.join(",")} />
      <input type="hidden" name="ratios" value={ratios.join(",")} />
      <input type="hidden" name="languages" value={languages.join(",")} />
      <input type="hidden" name="concepts" value={concepts} />
      <input type="hidden" name="hooksPerConcept" value={hooksPerConcept} />
      <input type="hidden" name="durationSeconds" value={durationSeconds} />
      <input type="hidden" name="quality" value={quality} />
      <input type="hidden" name="withVoiceover" value={String(withVoiceover)} />
      <input type="hidden" name="withThumbnail" value={String(withThumbnail)} />
      <input type="hidden" name="stage" value={stage} />
      <input type="hidden" name="lengthDays" value={lengthDays} />
      <input type="hidden" name="tone" value={tone} />
      <input type="hidden" name="goal" value={goal} />
      {/* `productionMode` is NOT hidden — the selector's radios carry that name
          and post it themselves. A hidden field of the same name would submit
          twice and the server would read whichever came first. */}
      <input type="hidden" name="withMusic" value={String(withMusic)} />
      {/* Posted so the server can verify the estimate it reserves against
          matches what the user was shown. It is a cross-check, never a source:
          the server recomputes from the same module and refuses on mismatch
          rather than trusting a client-supplied price. */}
      <input type="hidden" name="quotedCredits" value={modeEstimate.credits} />

      <div className="flex min-w-0 flex-col gap-[var(--app-panel-gap)] xl:col-span-7">
        <BriefCard prompt={prompt} onPromptChange={setPrompt} promptReady={promptReady} />

        <AudienceCard
          goal={goal}
          onGoalChange={(next) => {
            setGoal(next);
            // The shape no longer matches the template that set it.
            setTemplateId(null);
          }}
          tone={tone}
          onToneChange={setTone}
          languages={languages}
          onLanguagesChange={setLanguages}
        />

        <ShapeCard
          lengthDays={lengthDays}
          onLengthChange={(next) => {
            setLengthDays(next);
            setTemplateId(null);
          }}
          platforms={platforms}
          onPlatformToggle={(id) => toggle(platforms, id, setPlatforms)}
          ratios={ratios}
          onRatioToggle={(id) => toggle(ratios, id, setRatios)}
          quality={quality}
          onQualityChange={setQuality}
          concepts={concepts}
          onConceptsChange={(next) => {
            setConcepts(next);
            setTemplateId(null);
          }}
          hooksPerConcept={hooksPerConcept}
          onHooksChange={setHooksPerConcept}
          durationSeconds={durationSeconds}
          onDurationChange={setDurationSeconds}
          withVoiceover={withVoiceover}
          onVoiceoverToggle={() => setWithVoiceover((value) => !value)}
          withThumbnail={withThumbnail}
          onThumbnailToggle={() => setWithThumbnail((value) => !value)}
          withMusic={withMusic}
          onMusicToggle={() => setWithMusic((value) => !value)}
        />

        {/* Placed after the shape and before the templates: the mode is chosen
            once the campaign's size is known, because its per-reel price only
            means something against a count. */}
        <ProductionModePanel
          modes={PRODUCTION_MODE_DEFAULTS}
          selected={mode}
          onSelect={(next) => {
            setMode(next);
            // Re-arm confirmation: the cost the user confirmed is no longer the
            // cost they would be charged.
            setConfirmed(false);
          }}
          batchCredits={batchCredits}
          unmetered={unmetered}
        />

        <TemplateCard activeId={templateId} onApply={applyTemplate} />
      </div>

      {/*
        The plan column, pinned while the brief is edited — that is the whole
        point of it being a column rather than a section below the form.

        It carries its own scroller because the three cards together are taller
        than a laptop viewport: a `sticky` block taller than its container pins at
        the top and its lower half, including the submit button, becomes
        unreachable. The horizontal padding keeps focus rings from being clipped
        by that scroller.
      */}
      <aside
        className={cn(
          "flex min-w-0 flex-col gap-[var(--app-panel-gap)] xl:col-span-5",
          "xl:sticky xl:top-[calc(var(--app-topbar-height)+var(--space-6))]",
          "xl:max-h-[calc(100dvh-var(--app-topbar-height)-var(--space-12))]",
          "xl:overflow-y-auto xl:px-[var(--space-1)]",
        )}
      >
        <PlanSummaryCard
          work={modeEstimate.work}
          estimatedMinutes={estimate.estimatedMinutes}
          errors={errors.map((error) => error.message)}
        />

        <CreditPanel comparison={comparison} reserved={creditsReserved} unmetered={unmetered} />

        <StageCard
          stage={stage}
          onStageChange={(next) => {
            setStage(next);
            // Re-arm confirmation when the expensive option is chosen.
            setConfirmed(false);
          }}
          gateOnConfirmation={gateOnConfirmation}
          confirmed={confirmed}
          onConfirmedChange={setConfirmed}
          totalJobs={modeEstimate.work.totalJobs}
          canSubmit={canSubmit}
          promptReady={promptReady}
          gateCredits={gateCredits}
          unmetered={unmetered}
        />
      </aside>
    </form>
  );
}

/* ==========================================================================
   THE BRIEF
   ======================================================================== */

/** The brief input and its source actions. */
function BriefCard({
  prompt,
  onPromptChange,
  promptReady,
}: {
  prompt: string;
  onPromptChange: (next: string) => void;
  promptReady: boolean;
}) {
  return (
    <Card as="section" aria-labelledby="brief-heading">
      <CardHeader id="brief-heading" as="h2" title={briefPanelCopy.heading} />

      <CardBody className="pt-[var(--space-3)]">
        {/* A real label, not placeholder-only instruction, and the hint below it
            is rendered for everyone — essential instructions never live only in
            a placeholder. */}
        <div className="flex items-baseline justify-between gap-[var(--space-4)]">
          <label htmlFor="campaign-brief" className={labelClasses}>
            {createCopy.promptLabel}
          </label>
          <span
            className={cn(
              "app-figure text-[length:var(--text-app-label)]",
              prompt.length > BRIEF_MAX * 0.9
                ? "text-[color:var(--warning)]"
                : "text-[color:var(--text-muted)]",
            )}
          >
            {prompt.length.toLocaleString("en-US")} / {BRIEF_MAX.toLocaleString("en-US")}
          </span>
        </div>

        <textarea
          id="campaign-brief"
          name="promptVisible"
          rows={7}
          value={prompt}
          maxLength={BRIEF_MAX}
          onChange={(event) => onPromptChange(event.target.value)}
          aria-describedby="campaign-brief-hint"
          placeholder={createCopy.examples[0]}
          className={cn(
            "mt-[var(--space-2)] w-full resize-y rounded-[var(--radius-control)]",
            "border border-[var(--border-default)] bg-[var(--surface-primary)] p-[var(--space-3)]",
            "[font-family:inherit] text-[length:var(--text-app-body)] text-[color:var(--text-primary)]",
            "placeholder:text-[color:var(--text-muted)]",
            "transition-colors duration-[var(--dur-instant)]",
            "hover:border-[var(--border-strong)]",
            "focus:border-[var(--brand-primary)] focus:outline-2 focus:outline-offset-1 focus:outline-[var(--focus-ring)]",
          )}
        />

        <p id="campaign-brief-hint" className={cn("mt-[var(--space-2)]", hintClasses)}>
          {createCopy.promptHint}
        </p>

        {!promptReady && prompt.length > 0 && (
          <p className="mt-[var(--space-2)] text-[length:var(--text-app-label)] text-[color:var(--warning)]">
            Write at least ten characters to continue.
          </p>
        )}

        {/* Source actions. Disabled and labelled rather than hidden, with the
            reason stated: the product will accept these sources, and a disabled
            control that explains itself is more honest than a button that
            silently does nothing. */}
        <div className="mt-[var(--space-5)] border-t border-[var(--border-subtle)] pt-[var(--space-4)]">
          <p className={labelClasses}>{briefPanelCopy.sourcesLabel}</p>

          <div className="mt-[var(--space-2)] flex flex-wrap items-center gap-[var(--space-2)]">
            <SourceButton icon={<Paperclip size={14} strokeWidth={1.75} />}>
              {briefPanelCopy.attachLabel}
            </SourceButton>
            <SourceButton icon={<Link2 size={14} strokeWidth={1.75} />}>
              {briefPanelCopy.urlLabel}
            </SourceButton>
            <SourceButton icon={<Upload size={14} strokeWidth={1.75} />}>
              {briefPanelCopy.uploadLabel}
            </SourceButton>
            <SourceButton icon={<Wand2 size={14} strokeWidth={1.75} />}>
              {briefPanelCopy.enhanceLabel}
            </SourceButton>
          </div>

          <p className={cn("mt-[var(--space-2)]", hintClasses)}>{briefPanelCopy.sourcesHint}</p>
        </div>
      </CardBody>
    </Card>
  );
}

/** A brief source action. Always disabled for now — see BriefCard. */
function SourceButton({ children, icon }: { children: ReactNode; icon: ReactNode }) {
  return (
    <button
      type="button"
      disabled
      className={cn(
        "flex h-8 cursor-not-allowed items-center gap-[var(--space-2)]",
        "rounded-[var(--radius-control)] border border-[var(--border-default)] px-[var(--space-3)]",
        "text-[length:var(--text-app-cell)] text-[color:var(--text-muted)] opacity-70",
      )}
    >
      <span aria-hidden="true" className="shrink-0">
        {icon}
      </span>
      {children}
    </button>
  );
}

/* ==========================================================================
   AUDIENCE AND TONE
   ======================================================================== */

/**
 * Goal, tone and languages.
 *
 * There is no audience field: who the campaign is for is part of the brief prose
 * and is not stored as its own column, so a control here would be a form field
 * with nowhere to go.
 */
function AudienceCard({
  goal,
  onGoalChange,
  tone,
  onToneChange,
  languages,
  onLanguagesChange,
}: {
  goal: string;
  onGoalChange: (next: string) => void;
  tone: string;
  onToneChange: (next: string) => void;
  languages: readonly string[];
  onLanguagesChange: (next: string[]) => void;
}) {
  const languagesId = useId();

  return (
    <Card as="section" aria-labelledby="audience-heading">
      <CardHeader id="audience-heading" as="h2" title={briefPanelCopy.audienceHeading} />

      <CardBody className="grid gap-[var(--space-4)] pt-[var(--space-3)] sm:grid-cols-2">
        <SelectField
          label="Primary goal"
          value={goal}
          onChange={onGoalChange}
          options={GOAL_OPTIONS}
        />
        <SelectField
          label="Tone of voice"
          value={tone}
          onChange={onToneChange}
          options={TONE_OPTIONS}
        />

        <div className="flex min-w-0 flex-col gap-[var(--space-1)]">
          <label htmlFor={languagesId} className={labelClasses}>
            Languages
          </label>
          <input
            id={languagesId}
            value={languages.join(", ")}
            aria-describedby={`${languagesId}-hint`}
            onChange={(event) =>
              onLanguagesChange(
                event.target.value
                  .split(",")
                  .map((value) => value.trim())
                  .filter(Boolean),
              )
            }
            className={controlClasses}
          />
          <p id={`${languagesId}-hint`} className={hintClasses}>
            Comma separated. Each is a separate script.
          </p>
        </div>
      </CardBody>
    </Card>
  );
}

/* ==========================================================================
   OUTPUT SHAPE
   ======================================================================== */

/** Volume, formats, channels, quality and the optional outputs. */
function ShapeCard({
  lengthDays,
  onLengthChange,
  platforms,
  onPlatformToggle,
  ratios,
  onRatioToggle,
  quality,
  onQualityChange,
  concepts,
  onConceptsChange,
  hooksPerConcept,
  onHooksChange,
  durationSeconds,
  onDurationChange,
  withVoiceover,
  onVoiceoverToggle,
  withThumbnail,
  onThumbnailToggle,
  withMusic,
  onMusicToggle,
}: {
  lengthDays: string;
  onLengthChange: (next: string) => void;
  platforms: readonly Platform[];
  onPlatformToggle: (id: Platform) => void;
  ratios: readonly AspectRatio[];
  onRatioToggle: (id: AspectRatio) => void;
  quality: Quality;
  onQualityChange: (next: Quality) => void;
  concepts: number;
  onConceptsChange: (next: number) => void;
  hooksPerConcept: number;
  onHooksChange: (next: number) => void;
  durationSeconds: number;
  onDurationChange: (next: number) => void;
  withVoiceover: boolean;
  onVoiceoverToggle: () => void;
  withThumbnail: boolean;
  onThumbnailToggle: () => void;
  withMusic: boolean;
  onMusicToggle: () => void;
}) {
  const qualityHint = QUALITY_OPTIONS.find((option) => option.id === quality)?.detail;

  return (
    <Card as="section" aria-labelledby="shape-heading">
      <CardHeader id="shape-heading" as="h2" title={briefPanelCopy.shapeHeading} />

      <CardBody className="flex flex-col gap-[var(--space-5)] pt-[var(--space-3)]">
        <fieldset className="min-w-0 border-0 p-0">
          <legend className={labelClasses}>{briefPanelCopy.volumeHeading}</legend>

          <div className="mt-[var(--space-3)] grid gap-[var(--space-4)] sm:grid-cols-2 lg:grid-cols-4">
            <SelectField
              label="Campaign length"
              value={lengthDays}
              onChange={onLengthChange}
              options={LENGTH_OPTIONS}
            />
            <NumberField
              label="Concepts"
              hint="Distinct angles on the brief."
              value={concepts}
              min={1}
              max={100}
              onChange={onConceptsChange}
            />
            <NumberField
              label="Hooks each"
              hint="Openings to test against each other."
              value={hooksPerConcept}
              min={1}
              max={10}
              onChange={onHooksChange}
            />
            <NumberField
              label="Seconds per video"
              hint="Target duration."
              value={durationSeconds}
              min={5}
              max={180}
              onChange={onDurationChange}
            />
          </div>
        </fieldset>

        <fieldset className="min-w-0 border-0 p-0">
          <legend className={labelClasses}>{briefPanelCopy.formatsHeading}</legend>

          <div className="mt-[var(--space-3)] flex flex-wrap gap-[var(--space-2)]">
            {RATIO_OPTIONS.map((option) => {
              const Icon = FORMAT_ICONS[option.id];
              return (
                <ToggleChip
                  key={option.id}
                  label={option.label}
                  detail={option.detail}
                  icon={<Icon size={14} strokeWidth={1.75} />}
                  selected={ratios.includes(option.id)}
                  onToggle={() => onRatioToggle(option.id)}
                />
              );
            })}
          </div>
        </fieldset>

        <fieldset className="min-w-0 border-0 p-0">
          <legend className={labelClasses}>{briefPanelCopy.channelsHeading}</legend>

          <div className="mt-[var(--space-3)] flex flex-wrap gap-[var(--space-2)]">
            {PLATFORM_OPTIONS.map((option) => (
              <ToggleChip
                key={option.id}
                label={option.label}
                selected={platforms.includes(option.id)}
                onToggle={() => onPlatformToggle(option.id)}
              />
            ))}
          </div>
        </fieldset>

        <div className="grid gap-[var(--space-5)] sm:grid-cols-2">
          <SelectField
            label="Quality"
            value={quality}
            onChange={onQualityChange}
            options={QUALITY_OPTIONS}
            hint={qualityHint}
          />

          <fieldset className="min-w-0 border-0 p-0">
            <legend className={labelClasses}>{briefPanelCopy.includeHeading}</legend>

            <div className="mt-[var(--space-3)] flex flex-wrap gap-[var(--space-2)]">
              <ToggleChip
                label="Voiceover"
                icon={<Mic size={14} strokeWidth={1.75} />}
                selected={withVoiceover}
                onToggle={onVoiceoverToggle}
              />
              <ToggleChip
                label="Thumbnails"
                icon={<ImageIcon size={14} strokeWidth={1.75} />}
                selected={withThumbnail}
                onToggle={onThumbnailToggle}
              />
              <ToggleChip
                label="Music"
                icon={<Music size={14} strokeWidth={1.75} />}
                selected={withMusic}
                onToggle={onMusicToggle}
              />
            </div>
          </fieldset>
        </div>
      </CardBody>
    </Card>
  );
}

/* ==========================================================================
   TEMPLATES
   ======================================================================== */

/** Quick templates. Configures the campaign's shape; never writes the brief. */
function TemplateCard({
  activeId,
  onApply,
}: {
  activeId: string | null;
  onApply: (id: string) => void;
}) {
  return (
    <Card
      as="section"
      id="templates"
      aria-labelledby="templates-heading"
      className="scroll-mt-[calc(var(--app-topbar-height)+var(--space-4))]"
    >
      <CardHeader
        id="templates-heading"
        as="h2"
        title={briefPanelCopy.templatesHeading}
        description={briefPanelCopy.templatesHint}
      />

      <CardBody className="pt-[var(--space-4)]">
        <ul className="grid gap-[var(--space-3)] sm:grid-cols-2 lg:grid-cols-4">
          {TEMPLATES.map((template) => {
            const active = template.id === activeId;
            return (
              <li key={template.id}>
                <button
                  type="button"
                  onClick={() => onApply(template.id)}
                  aria-pressed={active}
                  className={cn(
                    "flex h-full w-full flex-col items-start gap-[var(--space-2)] text-left",
                    "rounded-[var(--radius-control)] p-[var(--space-3)]",
                    "transition-colors duration-[var(--dur-instant)] ease-[var(--ease-cut)]",
                    "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--focus-ring)]",
                    active
                      ? // Compensates for the extra border pixel so applying a
                        // template does not shift its neighbours.
                        "border-2 border-[var(--brand-primary)] bg-[var(--brand-soft)] p-[calc(var(--space-3)-1px)]"
                      : "border border-[var(--border-default)] hover:border-[var(--border-strong)] hover:bg-[var(--surface-secondary)]",
                  )}
                >
                  <span className="flex w-full items-baseline justify-between gap-[var(--space-2)]">
                    <span
                      className={cn(
                        "text-[length:var(--text-app-cell)] font-[var(--weight-strong)]",
                        active
                          ? "text-[color:var(--brand-ink)]"
                          : "text-[color:var(--text-primary)]",
                      )}
                    >
                      {template.label}
                    </span>
                    {/* Shape redundancy for the applied state, with the width
                        reserved so the row does not reflow. */}
                    <span aria-hidden="true" className="w-4 shrink-0">
                      {active && (
                        <Check
                          size={14}
                          strokeWidth={2.5}
                          className="text-[color:var(--brand-mark)]"
                        />
                      )}
                    </span>
                  </span>

                  <span className={cn("app-figure", hintClasses)}>
                    {template.range} · {template.concepts} concepts
                  </span>

                  {/* What the brief must cover. This is the template's actual
                      value — it tells the user what to write rather than writing
                      it for them. */}
                  <span className="flex flex-col gap-0.5">
                    {template.covers.map((item) => (
                      <span key={item} className={cn("flex gap-[var(--space-2)]", hintClasses)}>
                        <span aria-hidden="true">·</span>
                        {item}
                      </span>
                    ))}
                  </span>
                </button>
              </li>
            );
          })}
        </ul>
      </CardBody>
    </Card>
  );
}

/* ==========================================================================
   THE PLAN COLUMN
   ======================================================================== */

/**
 * What the batch will produce.
 *
 * Every figure comes from `lib/creative/estimator`, which is the module the
 * server reserves credits against — so the counts here and the price in the
 * credit card describe the same batch. Nothing is illustrative.
 */
function PlanSummaryCard({
  work,
  estimatedMinutes,
  errors,
}: {
  work: ReturnType<typeof estimateBatch>["work"];
  estimatedMinutes: { low: number; high: number } | null;
  errors: readonly string[];
}) {
  const count = (value: number) => value.toLocaleString("en-US");

  return (
    <Card as="section" aria-labelledby="plan-summary">
      <CardHeader
        id="plan-summary"
        as="h2"
        title={planSummaryCopy.heading}
        description={planSummaryCopy.intro}
      />

      <CardBody className="flex flex-col gap-[var(--space-4)] pt-[var(--space-3)]">
        {errors.length > 0 && (
          <ErrorState
            title="Plan not valid"
            body={errors.join(" ")}
            reassurance="Nothing has been created and no credits have been used."
          />
        )}

        <FigureList>
          <FigureRow
            label="Content items"
            value={count(work.contentItems)}
            icon={<FileText size={14} strokeWidth={1.75} />}
          />
          <FigureRow
            label="Platform variants"
            value={count(work.variants)}
            icon={<Layers size={14} strokeWidth={1.75} />}
          />
          <FigureRow label="Scripts" value={count(work.scripts)} />
          <FigureRow
            label="Generated images"
            value={count(work.generatedImages)}
            icon={<ImageIcon size={14} strokeWidth={1.75} />}
          />
          <FigureRow
            label="AI video clips"
            value={count(work.aiVideoClips)}
            icon={<Film size={14} strokeWidth={1.75} />}
          />
          {work.voiceovers > 0 && (
            <FigureRow
              label="Voiceovers"
              value={count(work.voiceovers)}
              icon={<Mic size={14} strokeWidth={1.75} />}
            />
          )}
          {work.musicTracks > 0 && (
            <FigureRow
              label="Music tracks"
              value={count(work.musicTracks)}
              icon={<Music size={14} strokeWidth={1.75} />}
            />
          )}
          <FigureRow
            label="Compositions to render"
            value={count(work.renders)}
            icon={<Monitor size={14} strokeWidth={1.75} />}
          />
          {work.publishJobs > 0 && (
            <FigureRow
              label="Publishing jobs"
              value={count(work.publishJobs)}
              icon={<Radio size={14} strokeWidth={1.75} />}
            />
          )}

          <FigureRow label="Total jobs" value={count(work.totalJobs)} emphasis divided />

          {/* Rendered only when provider throughput is actually known. A time
              estimate may come from measured throughput and from nothing else,
              so with no provider configured there is no row here rather than an
              invented range. */}
          {estimatedMinutes !== null && (
            <FigureRow
              label="Estimated time"
              value={`~${estimatedMinutes.low}–${estimatedMinutes.high} min`}
            />
          )}
        </FigureList>

        {estimatedMinutes === null && <p className={hintClasses}>{costCopy.noTimeEstimate}</p>}

        <PanelNote title={planSummaryCopy.whyHeading} body={planSummaryCopy.whyBody} />
      </CardBody>
    </Card>
  );
}

/**
 * How far to go now, and the commit.
 *
 * The submit button lives here rather than beside the brief because this column
 * is pinned: the primary action stays on screen while the form is edited, and one
 * primary action is clearer than two identical ones on the same page.
 */
function StageCard({
  stage,
  onStageChange,
  gateOnConfirmation,
  confirmed,
  onConfirmedChange,
  totalJobs,
  canSubmit,
  promptReady,
  gateCredits,
  unmetered,
}: {
  stage: GenerationGateId;
  onStageChange: (next: GenerationGateId) => void;
  gateOnConfirmation: boolean;
  confirmed: boolean;
  onConfirmedChange: (next: boolean) => void;
  totalJobs: number;
  canSubmit: boolean;
  promptReady: boolean;
  /** Credits each gate spends under the selected production mode. */
  gateCredits: Readonly<Record<GenerationGateId, number>>;
  unmetered: boolean;
}) {
  return (
    <Card as="section" aria-labelledby="plan-stage">
      <CardHeader
        id="plan-stage"
        as="h2"
        title={costCopy.stageHeading}
        description={costCopy.stageHint}
      />

      <CardBody className="pt-[var(--space-4)]">
        <fieldset className="min-w-0 border-0 p-0">
          <legend className="sr-only">{costCopy.stageHeading}</legend>

          <div className="flex flex-col gap-[var(--space-2)]">
            {GENERATION_GATES.map((option) => {
              const selected = stage === option.id;
              const credits = gateCredits[option.id] ?? 0;
              return (
                <label
                  key={option.id}
                  className={cn(
                    "flex cursor-pointer items-start gap-[var(--space-3)]",
                    "rounded-[var(--radius-control)] p-[var(--space-3)]",
                    "transition-colors duration-[var(--dur-instant)]",
                    // The radio itself is visually hidden, so the ring has to be
                    // drawn on its label.
                    "has-[:focus-visible]:outline-2 has-[:focus-visible]:outline-offset-2 has-[:focus-visible]:outline-[var(--focus-ring)]",
                    selected
                      ? "border-2 border-[var(--brand-primary)] bg-[var(--brand-soft)] p-[calc(var(--space-3)-1px)]"
                      : "border border-[var(--border-default)] hover:border-[var(--border-strong)] hover:bg-[var(--surface-secondary)]",
                  )}
                >
                  <input
                    type="radio"
                    name="stageChoice"
                    value={option.id}
                    checked={selected}
                    onChange={() => onStageChange(option.id)}
                    className="sr-only"
                  />

                  <span aria-hidden="true" className="mt-0.5 w-3.5 shrink-0">
                    {selected && (
                      <Check
                        size={14}
                        strokeWidth={2.5}
                        className="text-[color:var(--brand-mark)]"
                      />
                    )}
                  </span>

                  <span className="flex min-w-0 flex-1 flex-col">
                    <span className="flex items-baseline justify-between gap-[var(--space-2)]">
                      <span
                        className={cn(
                          "text-[length:var(--text-app-cell)]",
                          selected
                            ? "text-[color:var(--brand-ink)]"
                            : "text-[color:var(--text-primary)]",
                        )}
                      >
                        {option.label}
                      </span>

                      {/* The gate's actual credit cost, not a binary "spends
                          credits" badge. The whole point of staging is choosing
                          how far to go, and that choice needs the number.
                          Suppressed when unmetered, where every gate is free. */}
                      {!unmetered && credits > 0 && (
                        <span className="app-figure shrink-0 text-[length:var(--text-app-label)] text-[color:var(--text-secondary)]">
                          {credits.toLocaleString("en-US")} credits
                        </span>
                      )}
                    </span>

                    <span className={hintClasses}>{option.produces}</span>
                  </span>
                </label>
              );
            })}
          </div>
        </fieldset>

        {gateOnConfirmation && (
          <div
            className={cn(
              "mt-[var(--space-4)] flex flex-col gap-[var(--space-3)]",
              "rounded-[var(--radius-control)] border border-[var(--warning-mark)]",
              "bg-[var(--warning-soft)] p-[var(--space-4)]",
            )}
          >
            <p className="text-[length:var(--text-app-cell)] font-[var(--weight-heading)] text-[color:var(--warning)]">
              {costCopy.confirmHeading}
            </p>
            <p className="text-[length:var(--text-app-meta)] text-[color:var(--text-primary)]">
              This will create {totalJobs.toLocaleString("en-US")} jobs and may use significant
              generation credits. Jobs run in controlled batches. Reviewing concepts first avoids
              unnecessary cost.
            </p>
            <label className="flex min-h-11 cursor-pointer items-center gap-[var(--space-3)] text-[length:var(--text-app-meta)] text-[color:var(--text-primary)]">
              <input
                type="checkbox"
                name="confirmed"
                checked={confirmed}
                onChange={(event) => onConfirmedChange(event.target.checked)}
                className="size-4 accent-[var(--brand-primary)]"
              />
              {costCopy.confirmCheckboxLabel}
            </label>
          </div>
        )}
      </CardBody>

      <CardBody className="border-t border-[var(--border-subtle)]">
        <p className="flex items-center gap-[var(--space-2)] text-[length:var(--text-app-cell)] font-[var(--weight-strong)] text-[color:var(--text-primary)]">
          {/* Not the machine-working teal: nothing is running yet. A settled
              state, with the word carrying the meaning. */}
          <span
            aria-hidden="true"
            className={cn(
              "size-1.5 shrink-0 rounded-[var(--radius-full)]",
              promptReady ? "bg-[var(--brand-mark)]" : "bg-[var(--text-muted)]",
            )}
          />
          {promptReady ? planSummaryCopy.readyLabel : planSummaryCopy.blockedLabel}
        </p>

        <p className={cn("mt-1", hintClasses)}>
          {promptReady
            ? planSummaryCopy.readyDetail
            : "Write a brief of at least ten characters to continue."}
        </p>

        <Button type="submit" size="lg" className="mt-[var(--space-4)] w-full" disabled={!canSubmit}>
          {createCopy.submitLabel}
        </Button>
      </CardBody>
    </Card>
  );
}

/* ==========================================================================
   CONTROLS

   Local to this page rather than taken from `app-ui/Controls`: those controls
   are 56px tall with a wide-tracked uppercase label inside the border, which is
   the density and the type treatment the light system replaced. They should be
   rebuilt there; until they are, the create page carries its own.
   ======================================================================== */

/**
 * A labelled select.
 *
 * A real `<select>`, not a custom listbox. Options are single-line strings with
 * no secondary content, which is exactly what the native element handles — and it
 * brings the mobile picker, type-ahead and the whole keyboard contract for free.
 */
function SelectField<T extends string>({
  label,
  value,
  onChange,
  options,
  hint,
}: {
  label: string;
  value: T;
  onChange: (next: T) => void;
  options: readonly { id: T; label: string }[];
  hint?: string;
}) {
  const id = useId();

  return (
    <div className="flex min-w-0 flex-col gap-[var(--space-1)]">
      <label htmlFor={id} className={labelClasses}>
        {label}
      </label>

      <div className="relative flex items-center">
        <select
          id={id}
          value={value}
          aria-describedby={hint ? `${id}-hint` : undefined}
          // A select's value is always one of the options it was given, which is
          // what the generic parameter states; the DOM only knows `string`.
          onChange={(event) => onChange(event.target.value as T)}
          className={cn(controlClasses, "cursor-pointer appearance-none pr-[var(--space-8)]")}
        >
          {options.map((option) => (
            <option key={option.id} value={option.id}>
              {option.label}
            </option>
          ))}
        </select>

        <ChevronDown
          aria-hidden="true"
          size={14}
          strokeWidth={1.75}
          className="pointer-events-none absolute right-[var(--space-3)] text-[color:var(--text-muted)]"
        />
      </div>

      {hint && (
        <p id={`${id}-hint`} className={hintClasses}>
          {hint}
        </p>
      )}
    </div>
  );
}

function NumberField({
  label,
  value,
  min,
  max,
  hint,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  hint: string;
  onChange: (next: number) => void;
}) {
  const id = useId();

  return (
    <div className="flex min-w-0 flex-col gap-[var(--space-1)]">
      <label htmlFor={id} className={labelClasses}>
        {label}
      </label>
      <input
        id={id}
        type="number"
        inputMode="numeric"
        min={min}
        max={max}
        value={value}
        aria-describedby={`${id}-hint`}
        onChange={(event) => {
          const next = Number(event.target.value);
          // Clamped on input rather than on submit: an out-of-range value would
          // otherwise silently change the estimate the user is reading.
          if (Number.isFinite(next)) onChange(Math.min(max, Math.max(min, Math.trunc(next))));
        }}
        className={cn(controlClasses, "app-figure")}
      />
      <p id={`${id}-hint`} className={hintClasses}>
        {hint}
      </p>
    </div>
  );
}

/**
 * A selectable chip — formats, channels, optional outputs.
 *
 * `aria-pressed` makes it a toggle button rather than a link that looks like one,
 * so assistive technology reports the state and not just the name. Selection
 * carries a border colour AND a wash AND a checkmark, never colour alone.
 *
 * 32px tall and text-labelled, so its target clears SC 2.5.8 on width; the 44px
 * inset is reserved for the icon-only controls that genuinely need it.
 */
function ToggleChip({
  label,
  detail,
  icon,
  selected,
  onToggle,
}: {
  label: string;
  detail?: string;
  icon?: ReactNode;
  selected: boolean;
  onToggle: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-pressed={selected}
      className={cn(
        "inline-flex h-8 items-center gap-[var(--space-2)] rounded-[var(--radius-control)] border",
        "px-[var(--space-3)] text-[length:var(--text-app-cell)]",
        "transition-colors duration-[var(--dur-instant)] ease-[var(--ease-cut)]",
        "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--focus-ring)]",
        selected
          ? "border-[var(--brand-primary)] bg-[var(--brand-soft)] text-[color:var(--brand-ink)]"
          : cn(
              "border-[var(--border-default)] bg-[var(--surface-primary)]",
              "text-[color:var(--text-secondary)]",
              "hover:border-[var(--border-strong)] hover:text-[color:var(--text-primary)]",
            ),
      )}
    >
      {icon && (
        <span
          aria-hidden="true"
          className={cn(
            "shrink-0",
            selected ? "text-[color:var(--brand-mark)]" : "text-[color:var(--text-muted)]",
          )}
        >
          {icon}
        </span>
      )}

      <span className="whitespace-nowrap">
        {label}
        {detail && (
          <span
            className={cn(
              "ml-[var(--space-2)] text-[length:var(--text-app-label)]",
              selected ? "text-[color:var(--brand-ink)]" : "text-[color:var(--text-muted)]",
            )}
          >
            {detail}
          </span>
        )}
      </span>

      {/* Shape redundancy for the selected state, with the width reserved so the
          chip does not resize on toggle. */}
      <span aria-hidden="true" className="w-3.5 shrink-0">
        {selected && (
          <Check size={13} strokeWidth={2.5} className="text-[color:var(--brand-mark)]" />
        )}
      </span>
    </button>
  );
}
