"use client";

import { useMemo, useState } from "react";
import type { AspectRatio, Platform } from "@/types/database";
import { cn } from "@/lib/cn";
import { Button } from "@/components/primitives/Button";
import { Field, Textarea } from "@/components/primitives/Field";
import { Input } from "@/components/primitives/Input";
import { Badge } from "@/components/primitives/Badge";
import { AuthMessage } from "@/components/auth/AuthMessage";
import {
  GENERATION_STAGES,
  DEFAULT_STAGE,
  estimateCost,
  formatCents,
  requiresConfirmation,
  validatePlanRequest,
  type GenerationStageId,
  type PlanRequest,
  type Quality,
} from "@/lib/content/plan";
import {
  PLATFORM_OPTIONS,
  QUALITY_OPTIONS,
  RATIO_OPTIONS,
  costCopy,
  createCopy,
} from "@/content/create";

/**
 * The campaign composer.
 *
 * Counts and cost are computed on every change from the same pure module the server
 * uses (`lib/content/plan`), so the number in the confirmation dialog is the number the
 * server will act on. Two implementations of that arithmetic would eventually disagree,
 * and the disagreement would be a bill the user did not agree to.
 *
 * Nothing is generated by this component. It builds a request and hands it to a server
 * action; the safe default stage is "plans only".
 */
export function Composer({
  onSubmit,
  accountCount,
  defaultLanguage,
}: {
  onSubmit: (payload: FormData) => void;
  accountCount: number;
  defaultLanguage: string;
}) {
  const [prompt, setPrompt] = useState("");
  const [platforms, setPlatforms] = useState<Platform[]>(["instagram", "tiktok"]);
  const [ratios, setRatios] = useState<AspectRatio[]>(["9:16"]);
  const [languages, setLanguages] = useState<string[]>([defaultLanguage]);
  const [concepts, setConcepts] = useState(3);
  const [hooksPerConcept, setHooksPerConcept] = useState(2);
  const [durationSeconds, setDurationSeconds] = useState(20);
  const [quality, setQuality] = useState<Quality>("standard");
  const [withVoiceover, setWithVoiceover] = useState(true);
  const [withThumbnail, setWithThumbnail] = useState(false);
  const [stage, setStage] = useState<GenerationStageId>(DEFAULT_STAGE);
  const [confirmed, setConfirmed] = useState(false);

  const request: PlanRequest = useMemo(
    () => ({
      concepts,
      hooksPerConcept,
      platforms,
      ratios,
      languages,
      accountCount,
      withVoiceover,
      withThumbnail,
      durationSeconds,
      quality,
    }),
    [
      concepts,
      hooksPerConcept,
      platforms,
      ratios,
      languages,
      accountCount,
      withVoiceover,
      withThumbnail,
      durationSeconds,
      quality,
    ],
  );

  const errors = useMemo(() => validatePlanRequest(request), [request]);
  const estimate = useMemo(() => estimateCost(request), [request]);
  const needsConfirmation = requiresConfirmation(estimate.counts);

  // Only the render stage actually spends the full estimate, so confirmation is
  // demanded for that combination rather than for any large plan.
  const gateOnConfirmation = needsConfirmation && stage === "render";
  const canSubmit =
    prompt.trim().length >= 10 && errors.length === 0 && (!gateOnConfirmation || confirmed);

  function toggle<T>(list: T[], value: T, setter: (next: T[]) => void, atLeastOne = true) {
    const has = list.includes(value);
    const next = has ? list.filter((item) => item !== value) : [...list, value];
    // Never allow an empty selection where the plan needs at least one — the user
    // would otherwise have to guess why the estimate disappeared.
    if (atLeastOne && next.length === 0) return;
    setter(next);
  }

  return (
    <form action={onSubmit} className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_22rem]">
      {/* Hidden fields carry the resolved request so the server does not re-derive it
          from loose inputs and risk computing something different. */}
      <input type="hidden" name="prompt" value={prompt} />
      <input type="hidden" name="platforms" value={platforms.join(",")} />
      <input type="hidden" name="ratios" value={ratios.join(",")} />
      <input type="hidden" name="languages" value={languages.join(",")} />
      <input type="hidden" name="concepts" value={concepts} />
      <input type="hidden" name="hooksPerConcept" value={hooksPerConcept} />
      <input type="hidden" name="durationSeconds" value={durationSeconds} />
      <input type="hidden" name="quality" value={quality} />
      <input type="hidden" name="withVoiceover" value={String(withVoiceover)} />
      <input type="hidden" name="withThumbnail" value={String(withThumbnail)} />
      <input type="hidden" name="stage" value={stage} />

      <div className="flex flex-col gap-8">
        <Field
          label={createCopy.promptLabel}
          hint={createCopy.promptHint}
          adornment={`${prompt.trim().length} characters`}
        >
          {({ inputId, describedBy }) => (
            <Textarea
              id={inputId}
              rows={6}
              value={prompt}
              onChange={(event) => setPrompt(event.target.value)}
              maxLength={4000}
              aria-describedby={describedBy}
              placeholder="A 7-day campaign about…"
            />
          )}
        </Field>

        <div>
          <p className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-muted)]">
            {createCopy.examplesLabel}
          </p>
          <ul className="mt-3 flex flex-col gap-2">
            {createCopy.examples.map((example) => (
              <li
                key={example}
                className="border-l-2 border-[var(--color-border-hairline)] pl-3 text-[length:var(--text-body-s)] text-[color:var(--color-text-muted)]"
              >
                {example}
              </li>
            ))}
          </ul>
        </div>

        <fieldset className="flex flex-col gap-3">
          <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
            Platforms
          </legend>
          <div className="flex flex-wrap gap-2">
            {PLATFORM_OPTIONS.map((option) => (
              <Chip
                key={option.id}
                label={option.label}
                selected={platforms.includes(option.id)}
                onToggle={() => toggle(platforms, option.id, setPlatforms)}
              />
            ))}
          </div>
        </fieldset>

        <fieldset className="flex flex-col gap-3">
          <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
            Formats
          </legend>
          <div className="flex flex-wrap gap-2">
            {RATIO_OPTIONS.map((option) => (
              <Chip
                key={option.id}
                label={option.label}
                detail={option.detail}
                selected={ratios.includes(option.id)}
                onToggle={() => toggle(ratios, option.id, setRatios)}
              />
            ))}
          </div>
        </fieldset>

        <div className="grid gap-6 sm:grid-cols-2">
          <NumberField label="Concepts" value={concepts} min={1} max={100} onChange={setConcepts}
            hint="Distinct angles on the brief." />
          <NumberField label="Hooks per concept" value={hooksPerConcept} min={1} max={10} onChange={setHooksPerConcept}
            hint="Openings to test against each other." />
          <NumberField label="Duration (seconds)" value={durationSeconds} min={5} max={180} onChange={setDurationSeconds}
            hint="Target length per video." />
          <Field label="Languages" hint="Comma separated. Each language is a separate script.">
            {({ inputId, describedBy }) => (
              <Input
                id={inputId}
                value={languages.join(", ")}
                onChange={(event) =>
                  setLanguages(
                    event.target.value
                      .split(",")
                      .map((value) => value.trim())
                      .filter(Boolean),
                  )
                }
                aria-describedby={describedBy}
              />
            )}
          </Field>
        </div>

        <fieldset className="flex flex-col gap-3">
          <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
            Quality
          </legend>
          <div className="flex flex-wrap gap-2">
            {QUALITY_OPTIONS.map((option) => (
              <Chip
                key={option.id}
                label={option.label}
                detail={option.detail}
                selected={quality === option.id}
                onToggle={() => setQuality(option.id)}
              />
            ))}
          </div>
        </fieldset>

        <fieldset className="flex flex-col gap-3">
          <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
            Include
          </legend>
          <div className="flex flex-wrap gap-2">
            <Chip label="Voiceover" selected={withVoiceover} onToggle={() => setWithVoiceover((v) => !v)} />
            <Chip label="Thumbnails" selected={withThumbnail} onToggle={() => setWithThumbnail((v) => !v)} />
          </div>
        </fieldset>
      </div>

      {/* Cost panel. Sticky on desktop so the numbers stay visible while options
          change — the whole point is that the user sees the consequence of a change
          at the moment they make it. */}
      <aside className="lg:sticky lg:top-20 lg:self-start">
        <div className="flex flex-col gap-6 rounded-[var(--radius-lg)] border border-[var(--color-border-hairline)] bg-[var(--color-surface-1)] p-6">
          <h2 className="font-utility text-[length:var(--text-utility)] uppercase tracking-[var(--tracking-utility)] text-[color:var(--color-text-secondary)]">
            {costCopy.heading}
          </h2>

          {errors.length > 0 && (
            <AuthMessage tone="error" body={errors.map((error) => error.message).join(" ")} />
          )}

          <dl className="flex flex-col gap-2">
            <CountRow label="Content items" value={estimate.counts.contentItems} />
            <CountRow label="Variants to publish" value={estimate.counts.variants} emphasis />
            <CountRow label="Videos to generate" value={estimate.counts.videos} />
            <CountRow label="Renders" value={estimate.counts.renders} />
            {estimate.counts.voiceovers > 0 && (
              <CountRow label="Voiceovers" value={estimate.counts.voiceovers} />
            )}
            {estimate.counts.publishJobs > 0 && (
              <CountRow label="Publishing jobs" value={estimate.counts.publishJobs} />
            )}
            <CountRow label="Total jobs" value={estimate.counts.totalJobs} />
          </dl>

          <div>
            <p className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-muted)]">
              {costCopy.breakdownHeading}
            </p>
            <ul className="mt-3 flex flex-col gap-1">
              {estimate.breakdown.map((row) => (
                <li
                  key={row.stage}
                  className="flex items-baseline justify-between gap-4 text-[length:var(--text-body-s)]"
                >
                  <span className="text-[color:var(--color-text-muted)]">
                    {row.stage}
                    <span className="ml-2 font-utility text-[length:var(--text-utility-xs)] tabular-nums">
                      ×{row.units.toLocaleString("en-US")}
                    </span>
                  </span>
                  <span className="font-utility tabular-nums text-[color:var(--color-text-secondary)]">
                    {formatCents(row.cents)}
                  </span>
                </li>
              ))}
            </ul>
            <p className="mt-3 flex items-baseline justify-between gap-4 border-t border-[var(--color-border-hairline)] pt-3">
              <span className="font-utility text-[length:var(--text-utility)] uppercase tracking-[var(--tracking-utility)] text-[color:var(--color-text-secondary)]">
                Total
              </span>
              <span className="font-utility text-[length:var(--text-title)] tabular-nums text-[color:var(--color-text-primary)]">
                {formatCents(estimate.totalCents)}
              </span>
            </p>
          </div>

          {/* No invented time range. The brief permits one only from real provider
              throughput, and there is none. */}
          {estimate.estimatedMinutes === null && (
            <p className="text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]">
              {costCopy.noTimeEstimate}
            </p>
          )}

          <fieldset className="flex flex-col gap-3">
            <legend className="font-utility text-[length:var(--text-utility-xs)] uppercase tracking-[var(--tracking-eyebrow)] text-[color:var(--color-text-secondary)]">
              {costCopy.stageHeading}
            </legend>
            <p className="text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]">
              {costCopy.stageHint}
            </p>
            <div className="flex flex-col gap-2">
              {GENERATION_STAGES.map((option) => (
                <label
                  key={option.id}
                  className={cn(
                    "flex min-h-11 cursor-pointer items-start gap-3 rounded-[var(--radius-sm)] border p-3",
                    "transition-colors duration-[var(--dur-instant)]",
                    stage === option.id
                      ? "border-2 border-[var(--color-action)] bg-[var(--color-action-wash)]"
                      : "border-[var(--color-border-hairline)] hover:border-[var(--color-border)]",
                  )}
                >
                  <input
                    type="radio"
                    name="stageChoice"
                    value={option.id}
                    checked={stage === option.id}
                    onChange={() => {
                      setStage(option.id);
                      // Re-arm confirmation when the destructive option is chosen.
                      setConfirmed(false);
                    }}
                    className="sr-only"
                  />
                  <span aria-hidden="true" className="w-3 font-utility text-[color:var(--color-action)]">
                    {stage === option.id ? "✓" : ""}
                  </span>
                  <span className="flex flex-col">
                    <span className="text-[length:var(--text-body-s)] text-[color:var(--color-text-primary)]">
                      {option.label}
                      {!option.cheap && (
                        <Badge tone="warning" className="ml-2">
                          Spends credits
                        </Badge>
                      )}
                    </span>
                    <span className="text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]">
                      {option.produces}
                    </span>
                  </span>
                </label>
              ))}
            </div>
          </fieldset>

          {gateOnConfirmation && (
            <div className="flex flex-col gap-3 rounded-[var(--radius-sm)] border border-[var(--color-warning)] p-4">
              <p className="font-utility text-[length:var(--text-utility)] uppercase tracking-[var(--tracking-utility)] text-[color:var(--color-warning)]">
                {costCopy.confirmHeading}
              </p>
              <p className="text-[length:var(--text-body-s)] text-[color:var(--color-text-secondary)]">
                This will create {estimate.counts.totalJobs.toLocaleString("en-US")} jobs and may
                use significant generation credits. Jobs run in controlled batches. Reviewing
                concepts first avoids unnecessary cost.
              </p>
              <label className="flex min-h-11 cursor-pointer items-center gap-3 text-[length:var(--text-body-s)] text-[color:var(--color-text-primary)]">
                <input
                  type="checkbox"
                  name="confirmed"
                  checked={confirmed}
                  onChange={(event) => setConfirmed(event.target.checked)}
                  className="size-4"
                />
                {costCopy.confirmCheckboxLabel}
              </label>
            </div>
          )}

          <Button type="submit" size="lg" className="w-full" disabled={!canSubmit}>
            {createCopy.submitLabel}
          </Button>

          {prompt.trim().length < 10 && (
            <p className="text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]">
              Write a brief of at least ten characters to continue.
            </p>
          )}
        </div>
      </aside>
    </form>
  );
}

/** Selection carries a border-weight change and a checkmark, never colour alone. */
function Chip({
  label,
  detail,
  selected,
  onToggle,
}: {
  label: string;
  detail?: string;
  selected: boolean;
  onToggle: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-pressed={selected}
      className={cn(
        "flex min-h-11 flex-col justify-center rounded-[var(--radius-sm)] border px-3 py-1.5 text-left",
        "transition-colors duration-[var(--dur-instant)] ease-[var(--ease-cut)]",
        "focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-focus)]",
        selected
          ? "border-2 border-[var(--color-action)] bg-[var(--color-action-wash)]"
          : "border-[var(--color-border-hairline)] hover:border-[var(--color-border)]",
      )}
    >
      <span className="flex items-center gap-1.5 text-[length:var(--text-body-s)] text-[color:var(--color-text-primary)]">
        <span aria-hidden="true" className="font-utility text-[color:var(--color-action)]">
          {selected ? "✓" : ""}
        </span>
        {label}
      </span>
      {detail && (
        <span className="text-[length:var(--text-utility-xs)] text-[color:var(--color-text-muted)]">
          {detail}
        </span>
      )}
    </button>
  );
}

function NumberField({
  label,
  value,
  min,
  max,
  hint,
  onChange,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  hint: string;
  onChange: (next: number) => void;
}) {
  return (
    <Field label={label} hint={hint}>
      {({ inputId, describedBy }) => (
        <Input
          id={inputId}
          type="number"
          inputMode="numeric"
          min={min}
          max={max}
          value={value}
          aria-describedby={describedBy}
          onChange={(event) => {
            const next = Number(event.target.value);
            // Clamped on input rather than on submit: an out-of-range value would
            // otherwise silently change the estimate the user is reading.
            if (Number.isFinite(next)) onChange(Math.min(max, Math.max(min, Math.trunc(next))));
          }}
        />
      )}
    </Field>
  );
}

function CountRow({
  label,
  value,
  emphasis,
}: {
  label: string;
  value: number;
  emphasis?: boolean;
}) {
  return (
    <div className="flex items-baseline justify-between gap-4">
      <dt
        className={cn(
          "text-[length:var(--text-body-s)]",
          emphasis ? "text-[color:var(--color-text-primary)]" : "text-[color:var(--color-text-muted)]",
        )}
      >
        {label}
      </dt>
      <dd
        className={cn(
          "font-utility tabular-nums",
          emphasis
            ? "text-[length:var(--text-title)] text-[color:var(--color-text-primary)]"
            : "text-[length:var(--text-body-s)] text-[color:var(--color-text-secondary)]",
        )}
      >
        {value.toLocaleString("en-US")}
      </dd>
    </div>
  );
}
