import type { AspectRatio } from "@/types/database";

/**
 * The canonical composition model.
 *
 * This is the thing the product actually sells. A finished reel is NOT the MP4
 * — the MP4 is a render of this, and it can be re-rendered at any size, in any
 * language, with any shot swapped, because everything needed to rebuild it
 * lives here.
 *
 * Storing only the output file would make "change this caption" mean
 * "regenerate the whole video", which is precisely the manual cost the product
 * exists to remove.
 *
 * Two invariants hold throughout and are asserted in composition.test.ts:
 *
 * Time is integer FRAMES, never seconds. A clip that starts at 1.5s is at frame
 * 45 at 30fps and frame 45 at 30fps only — storing seconds and multiplying at
 * render time produces off-by-one drift that desynchronises audio from captions
 * across a 60-second reel.
 *
 * Layout is NORMALISED (0..1), never pixels. That is what makes one composition
 * renderable at 1080×1920 and 1080×1350 without a second layout pass, and it is
 * why format adaptation is cheap.
 */

export const SUPPORTED_RATIOS: readonly AspectRatio[] = [
  "9:16",
  "4:5",
  "1:1",
  "16:9",
  "4:3",
  "custom",
];

/** Pixel dimensions for each ratio at the product's standard export height. */
const RATIO_DIMENSIONS: Readonly<Record<string, { width: number; height: number }>> = {
  "9:16": { width: 1080, height: 1920 },
  "4:5": { width: 1080, height: 1350 },
  "1:1": { width: 1080, height: 1080 },
  "16:9": { width: 1920, height: 1080 },
  "4:3": { width: 1440, height: 1080 },
  "3:2": { width: 1620, height: 1080 },
};

export function dimensionsFor(ratio: AspectRatio): { width: number; height: number } {
  const known = RATIO_DIMENSIONS[ratio];
  if (known) return known;
  // `custom` has no fixed size. Defaulting to 9:16 rather than throwing keeps a
  // legacy row renderable, and the studio requires explicit dimensions for
  // custom before it will export.
  return RATIO_DIMENSIONS["9:16"]!;
}

/**
 * A rectangle in normalised coordinates.
 *
 * All four values are 0..1 fractions of the frame. Resolution-independent by
 * construction, which is the property format adaptation depends on.
 */
export type NormalisedBox = {
  x: number;
  y: number;
  width: number;
  height: number;
};

export type TrackKind = "video" | "image" | "voice" | "music" | "sfx" | "caption" | "overlay";

/** One item on a track, positioned in frames. */
export type CompositionClip = {
  id: string;
  /** Inclusive. */
  startFrame: number;
  /** Exclusive, so `endFrame - startFrame` is the duration with no off-by-one. */
  endFrame: number;
  /** Media backing this clip. Null for pure-text overlays and captions. */
  mediaAssetId: string | null;
  /** Where in the source media to start, for trimmed clips. */
  sourceOffsetFrames: number;
  box: NormalisedBox;
  /** Text for caption and overlay clips. */
  text: string | null;
  /**
   * Ken Burns / camera movement, expressed as start and end boxes.
   *
   * This is what makes Fast Reels work: motion over a still image, computed by
   * Remotion rather than generated by a video model at 90 cents a clip.
   */
  motion: { from: NormalisedBox; to: NormalisedBox } | null;
  transitionInFrames: number;
  transitionOutFrames: number;
  /** 0..1. Applies to audio tracks; ignored on visual ones. */
  volume: number;
};

export type CompositionTrack = {
  id: string;
  kind: TrackKind;
  /** Higher renders on top. Audio tracks mix regardless of this. */
  layer: number;
  muted: boolean;
  clips: readonly CompositionClip[];
};

/**
 * Per-platform deviations from the base composition.
 *
 * An override is a PATCH, not a copy. Storing whole alternative compositions
 * would mean a script fix had to be applied five times and would be applied
 * four times in practice.
 */
export type PlatformCompositionOverride = {
  ratio: AspectRatio;
  /** Frames trimmed from the end, for platforms with shorter limits. */
  trimEndFrames: number;
  /** Vertical caption position for this ratio, normalised. */
  captionY: number | null;
  /** Safe-area insets this platform's own UI covers. */
  safeArea: { top: number; bottom: number; left: number; right: number } | null;
};

export type Composition = {
  id: string;
  width: number;
  height: number;
  fps: number;
  durationFrames: number;
  templateId: string;
  ratio: AspectRatio;
  tracks: readonly CompositionTrack[];
  platformOverrides: readonly PlatformCompositionOverride[];
  brand: BrandStyle;
};

export type BrandStyle = {
  primaryColor: string;
  textColor: string;
  fontFamily: string;
  logoAssetId: string | null;
};

// --- Safe areas -------------------------------------------------------------

/**
 * Regions each platform's own interface covers.
 *
 * Measured as fractions of frame height/width. These are conservative estimates
 * from published design guidance, not pixel-measured captures — a caption that
 * sits just inside a real overlay is a caption nobody reads, so the values err
 * toward keeping content further in.
 */
export const PLATFORM_SAFE_AREAS: Readonly<
  Record<string, { top: number; bottom: number; left: number; right: number }>
> = {
  // Bottom is large: caption text, handle, audio attribution and the action rail.
  tiktok: { top: 0.08, bottom: 0.22, left: 0.04, right: 0.16 },
  instagram: { top: 0.1, bottom: 0.2, left: 0.04, right: 0.14 },
  youtube: { top: 0.06, bottom: 0.18, left: 0.04, right: 0.14 },
  facebook: { top: 0.08, bottom: 0.18, left: 0.04, right: 0.12 },
};

export function safeAreaFor(platform: string) {
  return PLATFORM_SAFE_AREAS[platform] ?? { top: 0.05, bottom: 0.1, left: 0.04, right: 0.04 };
}

/** True when a box lies entirely inside the platform's safe area. */
export function isInsideSafeArea(box: NormalisedBox, platform: string): boolean {
  const safe = safeAreaFor(platform);
  return (
    box.x >= safe.left &&
    box.y >= safe.top &&
    box.x + box.width <= 1 - safe.right &&
    box.y + box.height <= 1 - safe.bottom
  );
}

// --- Format adaptation ------------------------------------------------------

/**
 * Re-frames a composition for a different aspect ratio.
 *
 * This is NOT a crop of a finished video. Each clip's normalised box is
 * recomputed so the subject stays framed, captions move to where they are
 * readable in the new shape, and the CTA lands inside the new safe area.
 *
 * The distinction matters commercially: cropping a 9:16 render to 16:9 cuts the
 * subject's head off and puts the captions off-screen, which is exactly the
 * manual rework the product claims to eliminate.
 */
export function adaptToRatio(
  composition: Composition,
  ratio: AspectRatio,
  platform: string,
): Composition {
  const { width, height } = dimensionsFor(ratio);
  const safe = safeAreaFor(platform);

  // How much the frame's shape changed. A 9:16 -> 16:9 move is a large
  // horizontal expansion, so visual boxes are re-centred rather than scaled
  // uniformly, which would leave the subject clinging to one edge.
  const sourceAspect = composition.width / composition.height;
  const targetAspect = width / height;
  const widened = targetAspect > sourceAspect;

  const tracks = composition.tracks.map((track) => ({
    ...track,
    clips: track.clips.map((clip) => ({
      ...clip,
      box: adaptBox(clip.box, { widened, safe, kind: track.kind }),
      motion: clip.motion
        ? {
            from: adaptBox(clip.motion.from, { widened, safe, kind: track.kind }),
            to: adaptBox(clip.motion.to, { widened, safe, kind: track.kind }),
          }
        : null,
    })),
  }));

  return {
    ...composition,
    width,
    height,
    ratio,
    tracks,
  };
}

function adaptBox(
  box: NormalisedBox,
  context: {
    widened: boolean;
    safe: { top: number; bottom: number; left: number; right: number };
    kind: TrackKind;
  },
): NormalisedBox {
  // Audio has no geometry. Returned unchanged rather than given a meaningless
  // box, so a bug in this function cannot silently mute a track.
  if (context.kind === "voice" || context.kind === "music" || context.kind === "sfx") {
    return box;
  }

  // Visual media fills the frame and is centred. A generated clip is the
  // subject; letterboxing it to preserve its original box would waste the frame
  // the user is paying for.
  if (context.kind === "video" || context.kind === "image") {
    return { x: 0, y: 0, width: 1, height: 1 };
  }

  // Captions and overlays are pinned inside the new safe area. In a widened
  // frame they also narrow, because a caption spanning a 16:9 frame is a line
  // too long to read at a glance.
  const usableWidth = 1 - context.safe.left - context.safe.right;
  const targetWidth = context.widened
    ? Math.min(box.width, usableWidth * 0.7)
    : Math.min(box.width, usableWidth);

  const x = context.safe.left + (usableWidth - targetWidth) / 2;
  const y = clamp(box.y, context.safe.top, 1 - context.safe.bottom - box.height);

  return { x, y, width: targetWidth, height: box.height };
}

function clamp(value: number, min: number, max: number): number {
  // `max` can fall below `min` when a tall element meets a large safe area.
  // Returning `min` keeps the element on screen; returning `max` would push it
  // off the top, which is worse than overlapping the bottom inset.
  if (max < min) return min;
  return Math.min(Math.max(value, min), max);
}

// --- Timing -----------------------------------------------------------------

/** Converts milliseconds to whole frames, rounding to the nearest. */
export function msToFrames(ms: number, fps: number): number {
  return Math.max(0, Math.round((ms / 1000) * fps));
}

export function framesToMs(frames: number, fps: number): number {
  return Math.round((frames / fps) * 1000);
}

/**
 * The composition's true duration: the last frame any clip occupies.
 *
 * Recomputed rather than trusted, because `durationFrames` is stored and an
 * edit that shortens the final clip would otherwise leave a stored duration
 * that renders seconds of black at the end.
 */
export function computeDurationFrames(tracks: readonly CompositionTrack[]): number {
  let last = 0;
  for (const track of tracks) {
    for (const clip of track.clips) {
      if (clip.endFrame > last) last = clip.endFrame;
    }
  }
  return last;
}

export type CompositionProblem = {
  code: string;
  message: string;
  clipId: string | null;
};

/**
 * Validates a composition before it is rendered.
 *
 * Rendering is the expensive step, so every fault that can be caught by reading
 * the model is caught here rather than after a minute of GPU time.
 */
export function validateComposition(composition: Composition): readonly CompositionProblem[] {
  const problems: CompositionProblem[] = [];

  if (composition.fps <= 0) {
    problems.push({ code: "invalid_fps", message: "Frame rate must be positive.", clipId: null });
  }
  if (composition.width <= 0 || composition.height <= 0) {
    problems.push({ code: "invalid_size", message: "Dimensions must be positive.", clipId: null });
  }

  const declared = composition.durationFrames;
  const actual = computeDurationFrames(composition.tracks);
  if (declared !== actual) {
    problems.push({
      code: "duration_mismatch",
      // A stored duration longer than the content renders trailing black frames,
      // which the quality check flags as a corrupt export.
      message: `Stored duration is ${declared} frames but the tracks end at ${actual}.`,
      clipId: null,
    });
  }

  for (const track of composition.tracks) {
    for (const clip of track.clips) {
      if (clip.endFrame <= clip.startFrame) {
        problems.push({
          code: "empty_clip",
          message: "A clip ends at or before it starts, so it would never appear.",
          clipId: clip.id,
        });
      }
      if (clip.startFrame < 0) {
        problems.push({
          code: "negative_start",
          message: "A clip starts before frame zero.",
          clipId: clip.id,
        });
      }
      if (
        (track.kind === "video" || track.kind === "image" || track.kind === "voice") &&
        clip.mediaAssetId === null
      ) {
        problems.push({
          code: "missing_media",
          message: "A media clip has no asset, so it would render as a gap.",
          clipId: clip.id,
        });
      }
      if (clip.volume < 0 || clip.volume > 1) {
        problems.push({
          code: "invalid_volume",
          message: "Volume must be between 0 and 1.",
          clipId: clip.id,
        });
      }
    }
  }

  // A reel with no visual track renders as audio over black.
  const hasVisual = composition.tracks.some(
    (track) => (track.kind === "video" || track.kind === "image") && track.clips.length > 0,
  );
  if (!hasVisual) {
    problems.push({
      code: "no_visual",
      message: "The composition has no video or image clips, so it would render black.",
      clipId: null,
    });
  }

  return problems;
}
