/**
 * @vitest-environment node
 *
 * Quality checks against REAL media, produced by the real ffmpeg binary.
 *
 * Synthetic fixtures rather than committed sample files: the faults being
 * detected — a silent track, a wrong aspect ratio, a truncated duration — have
 * to be constructed deliberately, and a repository of deliberately broken video
 * files is both large and impossible to review. Every fixture below is
 * generated by ffmpeg at test time from a filter graph that states exactly what
 * is wrong with it.
 *
 * These live in the integration suite because they shell out to real binaries
 * and write to disk. They need no database.
 */
import { execFile } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import ffmpegPath from "ffmpeg-static";
import { checkExport, isProbeAvailable, probeMedia, type QualityExpectation } from "./quality";

const run = promisify(execFile);
const FFMPEG = ffmpegPath as unknown as string | null;

let dir: string;

beforeAll(async () => {
  dir = await mkdtemp(join(tmpdir(), "virally-quality-"));
});

afterAll(async () => {
  await rm(dir, { recursive: true, force: true });
});

/** Renders a clip with ffmpeg and returns its path. */
async function fixture(
  name: string,
  args: readonly string[],
): Promise<string> {
  const path = join(dir, name);
  await run(FFMPEG!, ["-y", ...args, path]);
  return path;
}

/** A 1080×1920 h264 clip with an AAC tone — what a correct 9:16 export looks like. */
function goodClipArgs(durationSeconds: number, size = "1080x1920") {
  return [
    "-f", "lavfi", "-i", `testsrc=size=${size}:rate=30:duration=${durationSeconds}`,
    "-f", "lavfi", "-i", `sine=frequency=440:duration=${durationSeconds}`,
    "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest",
  ];
}

const EXPECTATION: QualityExpectation = {
  ratio: "9:16",
  expectedDurationMs: 2000,
  expectsAudio: true,
  minHeightPx: 1080,
};

describe.skipIf(!FFMPEG)("media probing (integration)", () => {
  it("reports ffprobe as available", () => {
    expect(isProbeAvailable()).toBe(true);
  });

  it("measures real dimensions, duration and codecs", async () => {
    const path = await fixture("good.mp4", goodClipArgs(2));
    const probe = await probeMedia(path);

    expect(probe.widthPx).toBe(1080);
    expect(probe.heightPx).toBe(1920);
    expect(probe.videoCodec).toBe("h264");
    expect(probe.audioCodec).toBe("aac");
    expect(probe.hasAudio).toBe(true);
    expect(probe.durationMs).toBeGreaterThanOrEqual(1900);
    expect(probe.durationMs).toBeLessThanOrEqual(2100);
    expect(probe.frameRate).toBe(30);
  });

  it("passes a correct export", async () => {
    const path = await fixture("pass.mp4", goodClipArgs(2));
    const report = await checkExport(path, EXPECTATION);

    expect(report.passed).toBe(true);
    expect(report.checks.find((c) => c.id === "aspect_ratio")?.status).toBe("pass");
    expect(report.checks.find((c) => c.id === "duration")?.status).toBe("pass");
    expect(report.checks.find((c) => c.id === "audio_present")?.status).toBe("pass");
  });

  it("fails an export whose aspect ratio is wrong", async () => {
    // The exact bug this catches: a 16:9 render escaping into a 9:16 slot,
    // which publishes letterboxed or cropped through the subject's face.
    const path = await fixture("wrong-ratio.mp4", goodClipArgs(2, "1920x1080"));
    const report = await checkExport(path, EXPECTATION);

    expect(report.passed).toBe(false);
    expect(report.checks.find((c) => c.id === "aspect_ratio")?.status).toBe("fail");
  });

  it("fails an export with no audio when a voice track was composed", async () => {
    // The composition had a voiceover; the mix dropped it. The video looks
    // perfect and is silent, which no visual check would ever catch.
    const path = await fixture("silent.mp4", [
      "-f", "lavfi", "-i", "testsrc=size=1080x1920:rate=30:duration=2",
      "-c:v", "libx264", "-pix_fmt", "yuv420p", "-an",
    ]);
    const report = await checkExport(path, EXPECTATION);

    expect(report.passed).toBe(false);
    const check = report.checks.find((c) => c.id === "audio_present");
    expect(check?.status).toBe("fail");
    expect(check?.detail).toContain("voice track");
  });

  it("passes a silent export when no voice track was expected", async () => {
    const path = await fixture("silent-ok.mp4", [
      "-f", "lavfi", "-i", "testsrc=size=1080x1920:rate=30:duration=2",
      "-c:v", "libx264", "-pix_fmt", "yuv420p", "-an",
    ]);
    const report = await checkExport(path, { ...EXPECTATION, expectsAudio: false });
    expect(report.passed).toBe(true);
  });

  it("fails an export whose duration disagrees with the composition", async () => {
    // A render that disagrees with its own timeline has dropped or repeated
    // frames — the audio will drift against the captions.
    const path = await fixture("short.mp4", goodClipArgs(1));
    const report = await checkExport(path, EXPECTATION);

    expect(report.passed).toBe(false);
    expect(report.checks.find((c) => c.id === "duration")?.status).toBe("fail");
  });

  it("accepts sub-second duration drift", async () => {
    const path = await fixture("close.mp4", goodClipArgs(2));
    const report = await checkExport(path, { ...EXPECTATION, expectedDurationMs: 2200 });
    expect(report.checks.find((c) => c.id === "duration")?.status).toBe("pass");
  });

  it("fails a corrupt file rather than throwing", async () => {
    const path = join(dir, "corrupt.mp4");
    await writeFile(path, Buffer.from("this is not a video file, it is a sentence"));

    const report = await checkExport(path, EXPECTATION);
    expect(report.passed).toBe(false);
    expect(report.checks.find((c) => c.id === "decodable")?.status).toBe("fail");
    expect(report.probe).toBeNull();
  });

  it("warns rather than fails on a low-resolution export", async () => {
    // Soft-looking output is still publishable. Blocking on it would make the
    // gate something users learn to click past.
    const path = await fixture("small.mp4", goodClipArgs(2, "540x960"));
    const report = await checkExport(path, EXPECTATION);

    expect(report.checks.find((c) => c.id === "resolution")?.status).toBe("warn");
    expect(report.checks.find((c) => c.id === "aspect_ratio")?.status).toBe("pass");
    // Warnings do not block.
    expect(report.passed).toBe(true);
  });

  it("does not check aspect ratio for a custom-size composition", async () => {
    const path = await fixture("custom.mp4", goodClipArgs(2, "1234x1080"));
    const report = await checkExport(path, { ...EXPECTATION, ratio: "custom" });
    expect(report.checks.find((c) => c.id === "aspect_ratio")?.status).toBe("pass");
  });

  it("reports every failure, not only the first", async () => {
    const path = await fixture("multi-fail.mp4", [
      "-f", "lavfi", "-i", "testsrc=size=1920x1080:rate=30:duration=1",
      "-c:v", "libx264", "-pix_fmt", "yuv420p", "-an",
    ]);
    const report = await checkExport(path, EXPECTATION);

    const failed = report.checks.filter((c) => c.status === "fail").map((c) => c.id);
    expect(failed).toContain("aspect_ratio");
    expect(failed).toContain("duration");
    expect(failed).toContain("audio_present");
  });
});

describe.skipIf(FFMPEG)("media probing (integration)", () => {
  it("is skipped because ffmpeg-static is not installed", () => {
    expect(FFMPEG).toBeFalsy();
  });
});
